# til Makefile -- the bootstrap seam, and nothing else.
#
# make          Build bin/til (self-hosted compiler) + regenerate boot/
# make test     Build + run all tests
# make help     List every goal there is
#
# Build POLICY does not live here. It is make.til, compiled to bin/make
# (issue #345): which artifact depends on what, which command produces
# it, and what differs per host are ordinary til code, not a second
# language embedded in this file. What is left is the chicken-and-egg
# part a til program cannot do for itself -- produce the compiler that
# compiles it -- plus handing the requested goals over:
#
#   1. build the vendored libffi that the checked-in compiler C links
#   2. copy HEAD's boot/ and src/c/ out of git, compile bin/til_boot
#   3. compile make.til into bin/make with it
#   4. run bin/make ONCE with every requested goal
#
# `make <goals>` and `bin/make <goals>` are therefore the same build.
# bin/make is the direct interface (and takes real options, e.g. -j4);
# make stays the compatibility and clean-checkout interface.
#
# bin/til_boot  Built from the last commit via git (boot/ + src/c/ from
#               HEAD). Completely isolated from uncommitted changes.
#               Always safe. Rebuilt on every invocation, because its
#               real input is a commit, not a file make can stat.
# bin/til       Built by til_boot from ALL current sources (.til +
#               src/c/). Most .til and C changes take effect
#               immediately. Emit-side changes (e.g. new auto-gen
#               methods) need a preparation commit -- see doc/self.org.
# boot/         Generated C checked into the repo. Regenerated every
#               build so the next commit's til_boot has current code.
#
# Recovery: git checkout HEAD boot/ && make test

UNAME_S := $(shell uname -s)
UNAME_M := $(shell uname -m)

LIBFFI_DIR := vendor/libffi
# configure names its build directory after the host triple, which is
# not predictable here, so the archive is discovered rather than named.
LIBFFI_LIBDIR = $(firstword $(wildcard $(LIBFFI_DIR)/*/.libs))
LIBFFI_FLAGS = -L$(LIBFFI_LIBDIR) -lffi

CORE := $(wildcard src/core/*.til)
STD := $(wildcard src/std/*.til)
EXT_C := $(wildcard src/c/*.c) $(wildcard src/c/*.h)

# What bin/til_boot links, and all it links. The checked-in compiler C
# calls libffi directly (the interpreter's ext_func dispatch), and
# nothing else vendored: no raylib, tinyfd or nng function appears in
# boot/til.c or src/c/, so their archives contribute nothing to this
# link and their system dependencies (-lrt, -latomic, the macOS desktop
# frameworks) are not needed either. Verified by linking without them.
# make.til builds those libraries, because bin/til -- which does link
# them -- is its business, not the bootstrap's.
BOOT_LD_FLAGS := -rdynamic -ldl -lm -lpthread

# --- Goal delegation ---
#
# At parse time make already knows what was asked for, so there is no
# need for a catch-all pattern rule (which would need source-file guards
# and would swallow typos): the requested goals become phony frontends
# for one delegation target, which runs bin/make once with the whole
# list. Arbitrary path goals -- `make vendor/raylib/src/libraylib-x86.a`
# -- and multi-goal invocations both keep working, and no registry of
# til targets is duplicated here.
BOOTSTRAP_GOALS := bin/make bin/til_boot $(LIBFFI_DIR)/.built
DELEGATED := $(filter-out $(BOOTSTRAP_GOALS),$(MAKECMDGOALS))
ifeq ($(MAKECMDGOALS),)
DELEGATED := all
endif

# Command-line variables reach the build program unchanged. J is passed
# as the option bin/make spells it; the rest are read from the
# environment (bin/make also takes --riscv32-cc=<path> directly).
export RISCV32_CC EMCC EMAR EMRANLIB

ifneq ($(DELEGATED),)
.PHONY: .til-delegate $(DELEGATED)
# A real (silent) no-op recipe, not an empty one: without it make
# reports "Nothing to be done for 'bin/tests'" for every goal after the
# first, all of which the single delegation has already built.
$(DELEGATED): .til-delegate
	@:

.til-delegate: bin/make
	bin/make $(if $(J),-j$(J)) $(DELEGATED)
endif

# --- Bootstrap ---

# REM vendored libffi is release v3.7.1, vendored from the upstream git
# tag (the release-tarball hosts are unreachable from bot sessions) with
# `configure` and friends generated by autogen.sh (autoconf 2.71,
# automake 1.16, libtool 2.4.7 + libltdl-dev for ltdl.m4) -- issue #304.
# The 3.4.6-era local sysv.S cfi backport is upstream since 3.4.7;
# nothing local is patched into this tree anymore.
#
# This is the one vendored library the bootstrap needs, so it is the one
# that stays here. The cross-compiled libffi builds are make.til's.
$(LIBFFI_DIR)/.built:
	cd $(LIBFFI_DIR) && ./configure --disable-shared --enable-static --disable-docs --quiet
	$(MAKE) -C $(LIBFFI_DIR)
ifeq ($(UNAME_S),Darwin)
# configure names its build dir with a version-suffixed triple
# (aarch64-apple-darwin24.3.0), which targets.til cannot predict; keep a
# stable path for target_ffi_lib on mac hosts.
	cp $(LIBFFI_DIR)/*apple-darwin*/.libs/libffi.a $(LIBFFI_DIR)/libffi-macos.a
endif
ifeq ($(UNAME_S)-$(UNAME_M),Linux-aarch64)
# Same stable-path dance for native arm64 Linux hosts (the triple dir is
# aarch64-unknown-linux-gnu or aarch64-linux-gnu depending on config.guess).
	cp $(LIBFFI_DIR)/aarch64-*linux*/.libs/libffi.a $(LIBFFI_DIR)/libffi-linux-arm64.a
endif
	touch $@

# The recovery compiler: HEAD's committed boot/ and src/c/, extracted
# with git so no uncommitted edit can reach it, compiled here. .PHONY
# because its input is a commit and make cannot stat one -- a new HEAD
# has to reconstruct it, which worktree mtimes would not notice.
.PHONY: bin/til_boot
bin/til_boot: $(LIBFFI_DIR)/.built
	mkdir -p bin tmp/boot/boot tmp/boot/src/c
	for f in $$(git ls-tree --name-only HEAD boot/ 2>/dev/null); do \
		git show "HEAD:$$f" > "tmp/boot/$$f" 2>/dev/null || true; \
	done
	for f in $$(git ls-tree --name-only HEAD src/c/ 2>/dev/null); do \
		git show "HEAD:$$f" > "tmp/boot/$$f" 2>/dev/null || true; \
	done
	cc -Wall -Wextra -Werror -fsigned-char -g -Itmp/boot/src -Itmp/boot/src/c -Itmp/boot/boot tmp/boot/src/c/*.c tmp/boot/boot/til.c $(BOOT_LD_FLAGS) $(LIBFFI_FLAGS) -o bin/til_boot

# The build program itself: a generated artifact under the already
# ignored bin/ tree, never committed and never installed. bin/til_boot
# is an ORDER-ONLY prerequisite: bin/make must be built with it, but the
# bootstrap compiler is relinked on every invocation, so keying on its
# mtime would recompile the build program every time for nothing.
# Prerequisites otherwise mirror make.til's own self_sources(), so both
# entry points agree on when bin/make is stale.
bin/make: make.til $(CORE) $(STD) $(EXT_C) | bin/til_boot
	bin/til_boot build -o bin/make make.til
