#+TITLE: src/self/interpreter.til
#+SUBTITLE: til 0.0.1-4e407a330
#+OPTIONS: toc:t

* CALLABLE_BOX_MAGIC
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.CALLABLE_BOX_MAGIC
:group: Compiler tools
:END:

#+begin_src til
CALLABLE_BOX_MAGIC is a U64
#+end_src

* InterpCallableBox
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.InterpCallableBox
:group: Compiler tools
:END:

#+begin_src til
struct InterpCallableBox {
    mut magic : U64
    ref mut func_def : Expr
    mut env : Option__Scope
namespace:
    func size() returns shallow USize
    func clone(self: InterpCallableBox) returns InterpCallableBox
    func delete(own self: InterpCallableBox, shallow call_free: Bool)
}
#+end_src

* hb_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.hb_type
:group: Compiler tools
:END:

#+begin_src til
func hb_type(hb: HeapBinding) returns ref Type
#+end_src

* HeapBinding
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.HeapBinding
:group: Compiler tools
:END:

#+begin_src til
struct HeapBinding {
    ref mut ptr : U8
    ref mut til_type_p : U8
    mut own_type : OwnType
    ref mut ctx : Context
    mut is_local : Bool
    mut is_borrowed : Bool
    mut is_erased_dynamic : Bool
    mut is_static_callable : Bool
    mut moved_out : Bool
    mut is_raw_alloc : Bool
    mut payload_released : Bool
namespace:
    func size() returns shallow USize
    func clone(self: HeapBinding) returns HeapBinding
    func delete(own self: HeapBinding, shallow call_free: Bool)
}
#+end_src

* Scope
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Scope
:group: Compiler tools
:END:

#+begin_src til
struct Scope {
    mut heap_bindings : Map__Str_HeapBinding
    mut heap_aliases : Map__Str_Str
    mut parent : Option__ref_Scope
    mut is_call_scope : Bool
namespace:
    func size() returns shallow USize
    func clone(self: Scope) returns Scope
    func delete(own self: Scope, shallow call_free: Bool)
    func hash(self: Scope, hasher: HashFn) returns shallow U64
}
#+end_src

* InterpSession
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.InterpSession
:group: Compiler tools
:END:

#+begin_src til
struct InterpSession {
    mut global : Option__Scope
    mut core_evaluated : Bool
    mut user_argc : USize
    mut retained_programs : Vec__priv___src_self_interpreter_til__DynPtrBox
    mut is_repl : Bool
    mut evaluated_units : Set__Str
namespace:
    func size() returns shallow USize
    func clone(self: InterpSession) returns InterpSession
    func delete(own self: InterpSession, shallow call_free: Bool)
    func hash(self: InterpSession, hasher: HashFn) returns shallow U64
}
#+end_src

* lookup_interp_type_def
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.lookup_interp_type_def
:group: Compiler tools
:END:

#+begin_src til
func lookup_interp_type_def(name: Str, ctx: Context) returns shallow Option__ref_Expr
#+end_src

* enum_data_tag_key
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.enum_data_tag_key
:group: Compiler tools
:END:

#+begin_src til
func enum_data_tag_key(data: Dynamic, enum_def: Expr) returns shallow I64
#+end_src

* raw_type_is_prim
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.raw_type_is_prim
:group: Compiler tools
:END:

#+begin_src til
func raw_type_is_prim(shallow t: Type, ctx: Context) returns shallow Bool
#+end_src

* scalar_word_load
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scalar_word_load
:group: Compiler tools
:END:

#+begin_src til
func scalar_word_load(shallow t: Type, addr: Dynamic, ctx: Context) returns Dynamic
#+end_src

* field_word_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.field_word_type
:group: Compiler tools
:END:

#+begin_src til
func field_word_type(shallow ft: Type, shallow field_size: USize, ctx: Context) returns Type
#+end_src

* scalar_block_from_word
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scalar_block_from_word
:group: Compiler tools
:END:

#+begin_src til
func scalar_block_from_word(shallow t: Type, w: Dynamic, ctx: Context) returns Dynamic
#+end_src

* DISPATCH_SCRATCH_SLOTS
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.DISPATCH_SCRATCH_SLOTS
:group: Compiler tools
:END:

#+begin_src til
DISPATCH_SCRATCH_SLOTS is a USize
#+end_src

* WORD_RING_SLOTS
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.WORD_RING_SLOTS
:group: Compiler tools
:END:

#+begin_src til
WORD_RING_SLOTS is a USize
#+end_src

* raw_result_drop
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.raw_result_drop
:group: Compiler tools
:END:

#+begin_src til
proc raw_result_drop(shallow t: Type, mut raw: Dynamic, shallow return_is_ref: Bool, ctx: Context)
#+end_src

* scope_set_raw_owned
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_set_raw_owned
:group: Compiler tools
:END:

#+begin_src til
func scope_set_raw_owned(mut scope: Scope, name: Str, raw: Dynamic, t_w: Dynamic, own_type: OwnType, ctx: Context, shallow borrowed: Bool)
#+end_src

* eval_expr_raw
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.eval_expr_raw
:group: Compiler tools
:END:

#+begin_src til
proc eval_expr_raw(mut scope: Scope, mut e: Expr, mut ctx: Context, mut destination: Dynamic) returns Dynamic
#+end_src

* container_elem_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.container_elem_type
:group: Compiler tools
:END:

#+begin_src til
func container_elem_type(struct_name: Str, ctx: Context) returns Str
#+end_src

* container_elem_size
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.container_elem_size
:group: Compiler tools
:END:

#+begin_src til
func container_elem_size(elem_type: Str, ctx: Context) returns shallow USize
#+end_src

* container_live_count
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.container_live_count
:group: Compiler tools
:END:

#+begin_src til
func container_live_count(struct_name: Str, data: Dynamic, ctx: Context) returns shallow USize
#+end_src

* container_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.container_capacity
:group: Compiler tools
:END:

#+begin_src til
func container_capacity(struct_name: Str, data: Dynamic, ctx: Context) returns shallow USize
#+end_src

* scope_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_get
:group: Compiler tools
:END:

#+begin_src til
func scope_get(mut s: Scope, name: Str, mut _err_kind: I64) returns ref Dynamic
#+end_src

* scope_pool_drain
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_pool_drain
:group: Compiler tools
:END:

#+begin_src til
func scope_pool_drain()
#+end_src

* scope_new
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_new
:group: Compiler tools
:END:

#+begin_src til
func scope_new(parent: Option__ref_Scope) returns Scope
#+end_src

* scope_lookup_heap_binding
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_lookup_heap_binding
:group: Compiler tools
:END:

#+begin_src til
func scope_lookup_heap_binding(mut s: Scope, name: Str) returns shallow Option__ref_HeapBinding
#+end_src

* hb_func_def
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.hb_func_def
:group: Compiler tools
:END:

#+begin_src til
func hb_func_def(hb: HeapBinding) returns shallow Option__ref_Expr
#+end_src

* ns_func_def
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ns_func_def
:group: Compiler tools
:END:

#+begin_src til
func ns_func_def(sname: Str, fname: Str, mut ctx: Context) returns shallow Option__ref_Expr
#+end_src

* scope_read_bound_raw
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_read_bound_raw
:group: Compiler tools
:END:

#+begin_src til
func scope_read_bound_raw(mut scope: Scope, name: Str, ctx: Context) returns Dynamic
#+end_src

* interp_intern_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_intern_type
:group: Compiler tools
:END:

#+begin_src til
func interp_intern_type(shallow t: Type, mut ctx: Context) returns Dynamic
#+end_src

* scope_set_heap_owned
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_set_heap_owned
:group: Compiler tools
:END:

#+begin_src til
func scope_set_heap_owned(mut s: Scope, name: Str, ptr: Dynamic, til_type_w: Dynamic, own_type: OwnType, ctx: Context, shallow is_local: Bool, shallow is_borrowed: Bool, shallow is_erased_dynamic: Bool)
#+end_src

* scope_set_heap_moved
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_set_heap_moved
:group: Compiler tools
:END:

#+begin_src til
func scope_set_heap_moved(mut s: Scope, name: Str, shallow moved_out: Bool)
#+end_src

* scope_new_owned
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_new_owned
:group: Compiler tools
:END:

#+begin_src til
func scope_new_owned(parent: Option__ref_Scope) returns Scope
#+end_src

* scope_new_boxed
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_new_boxed
:group: Compiler tools
:END:

#+begin_src til
func scope_new_boxed(parent: Option__ref_Scope) returns ref Scope
#+end_src

* scope_drop_owned_bindings
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_drop_owned_bindings
:group: Compiler tools
:END:

#+begin_src til
func scope_drop_owned_bindings(mut s: Scope)
#+end_src

* scope_free
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.scope_free
:group: Compiler tools
:END:

#+begin_src til
func scope_free(own s: Scope)
#+end_src

* populate_cached_aggregate_defs
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.populate_cached_aggregate_defs
:group: Compiler tools
:END:

#+begin_src til
func populate_cached_aggregate_defs(mut ctx: Context, mut program: Expr)
#+end_src

* interpreter_init_ns
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interpreter_init_ns
:group: Compiler tools
:END:

#+begin_src til
proc interpreter_init_ns(mut ctx: Context, mut global: Scope, mut program: Expr)
#+end_src

* ns_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ns_get
:group: Compiler tools
:END:

#+begin_src til
func ns_get(sname: Str, fname: Str, mut ctx: Context) returns shallow Option__ref_Dynamic
#+end_src

* interpreter_free_ns
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interpreter_free_ns
:group: Compiler tools
:END:

#+begin_src til
func interpreter_free_ns(mut ctx: Context)
#+end_src

* str_cap_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.str_cap_at
:group: Compiler tools
:END:

#+begin_src til
func str_cap_at(str_base: Dynamic, ctx: Context) returns shallow USize
#+end_src

* str_count_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.str_count_at
:group: Compiler tools
:END:

#+begin_src til
func str_count_at(str_base: Dynamic, ctx: Context) returns shallow USize
#+end_src

* read_field
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.read_field
:group: Compiler tools
:END:

#+begin_src til
func read_field(inst_data: Dynamic, dd: Declaration, shallow field_offset: USize, shallow field_size: USize, ctx: Context) returns Dynamic
#+end_src

* interp_session_start
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_start
:group: Compiler tools
:END:

#+begin_src til
func interp_session_start(mut session: InterpSession, user_argv: Vec__Str)
#+end_src

* interp_session_free
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_free
:group: Compiler tools
:END:

#+begin_src til
func interp_session_free(mut session: InterpSession)
#+end_src

* interp_program_to_heap
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_program_to_heap
:group: Compiler tools
:END:

#+begin_src til
func interp_program_to_heap(own lp: LoadedProgram) returns Dynamic
#+end_src

* interp_program_free
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_program_free
:group: Compiler tools
:END:

#+begin_src til
func interp_program_free(raw: Dynamic)
#+end_src

* interp_session_retain_program
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_retain_program
:group: Compiler tools
:END:

#+begin_src til
func interp_session_retain_program(mut session: InterpSession, raw: Dynamic)
#+end_src

* interp_session_prepare_context
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_prepare_context
:group: Compiler tools
:END:

#+begin_src til
proc interp_session_prepare_context(mut session: InterpSession, mut lp: LoadedProgram, fwd_path: Str) returns shallow I32
#+end_src

* interp_session_finish_context
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_finish_context
:group: Compiler tools
:END:

#+begin_src til
proc interp_session_finish_context(mut lp: LoadedProgram)
#+end_src

* interp_session_eval_core_once
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_eval_core_once
:group: Compiler tools
:END:

#+begin_src til
proc interp_session_eval_core_once(mut session: InterpSession, mut lp: LoadedProgram)
#+end_src

* interp_session_eval_user_units
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_eval_user_units
:group: Compiler tools
:END:

#+begin_src til
proc interp_session_eval_user_units(mut session: InterpSession, mut lp: LoadedProgram)
#+end_src

* interp_session_eval_imported_once
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_eval_imported_once
:group: Compiler tools
:END:

#+begin_src til
proc interp_session_eval_imported_once(mut session: InterpSession, mut lp: LoadedProgram)
#+end_src

* interp_session_eval_current_root
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_eval_current_root
:group: Compiler tools
:END:

#+begin_src til
proc interp_session_eval_current_root(mut session: InterpSession, mut lp: LoadedProgram, shallow block_start_line: U32, shallow eval_doc_line: Bool, shallow doc_init_line: U32) returns shallow Bool
#+end_src

* interp_session_eval_current_tail
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.interp_session_eval_current_tail
:group: Compiler tools
:END:

#+begin_src til
proc interp_session_eval_current_tail(mut session: InterpSession, mut lp: LoadedProgram, shallow start_idx: USize, shallow count: USize) returns shallow Bool
#+end_src

* cmd_interpret
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.cmd_interpret
:group: Compiler tools
:END:

#+begin_src til
proc cmd_interpret(mut lp: LoadedProgram, user_argv: Vec__Str) returns shallow I32
#+end_src

* FFIEntry
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.FFIEntry
:group: Compiler tools
:END:

#+begin_src til
struct FFIEntry {
    ref mut fn : U8
    mut return_type : Option__ref_Str
    mut nparam : USize
    own mut param_shallows : U8
    own mut param_dynamics : U8
    mut return_is_shallow : Bool
    mut return_is_ref : Bool
    own mut cif : ffi_cif
    own mut arg_types : U8
namespace:
    func clone(self: FFIEntry) returns FFIEntry
    func size() returns shallow USize
    func delete(own self: FFIEntry, shallow call_free: Bool)
}
#+end_src

* ExprPtrBox
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ExprPtrBox
:group: Compiler tools
:END:

#+begin_src til
struct ExprPtrBox {
    ref mut ptr : Expr
namespace:
    func size() returns shallow USize
    func clone(self: ExprPtrBox) returns ExprPtrBox
    func delete(own self: ExprPtrBox, shallow call_free: Bool)
}
#+end_src

* FFITypePtrBox
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.FFITypePtrBox
:group: Compiler tools
:END:

#+begin_src til
struct FFITypePtrBox {
    own mut ptr : ffi_type
namespace:
    func clone(self: FFITypePtrBox) returns FFITypePtrBox
    func size() returns shallow USize
    func delete(own self: FFITypePtrBox, shallow call_free: Bool)
}
#+end_src

* ffi_reset
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_reset
:group: Compiler tools
:END:

#+begin_src til
proc ffi_reset(mut ctx: Context)
#+end_src

* ffi_load_global_lib
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_load_global_lib
:group: Compiler tools
:END:

#+begin_src til
ext_proc ffi_load_global_lib(soname: Str) returns shallow Bool
#+end_src

* ffi_open_user_so
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_open_user_so
:group: Compiler tools
:END:

#+begin_src til
ext_proc ffi_open_user_so(path: Str) returns shallow Bool
#+end_src

* ffi_close_user_so
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_close_user_so
:group: Compiler tools
:END:

#+begin_src til
ext_proc ffi_close_user_so()
#+end_src

* ffi_user_symbol
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_user_symbol
:group: Compiler tools
:END:

#+begin_src til
ext_func ffi_user_symbol(name: Str) returns ref U8
#+end_src

* ffi_global_symbol
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_global_symbol
:group: Compiler tools
:END:

#+begin_src til
ext_func ffi_global_symbol(name: Str) returns ref U8
#+end_src

* ffi_last_error
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_last_error
:group: Compiler tools
:END:

#+begin_src til
ext_proc ffi_last_error() returns Str
#+end_src

* til_built_with_asan
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.til_built_with_asan
:group: Compiler tools
:END:

#+begin_src til
ext_proc til_built_with_asan() returns shallow Bool
#+end_src

* ffi_init_struct_defs_append
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_init_struct_defs_append
:group: Compiler tools
:END:

#+begin_src til
func ffi_init_struct_defs_append(program: Expr, mut ctx: Context)
#+end_src

* dispatch_result_alloc
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.dispatch_result_alloc
:group: Compiler tools
:END:

#+begin_src til
func dispatch_result_alloc(t: Type, ctx: Context) returns Dynamic
#+end_src

* str_copy_into
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.str_copy_into
:group: Compiler tools
:END:

#+begin_src til
func str_copy_into(mut result: Dynamic, src: Str, ctx: Context)
#+end_src

* ffi_init_scan_program
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_init_scan_program
:group: Compiler tools
:END:

#+begin_src til
proc ffi_init_scan_program(program: Expr, mut ctx: Context)
#+end_src

* ffi_cleanup
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.ffi_cleanup
:group: Compiler tools
:END:

#+begin_src til
proc ffi_cleanup(mut ctx: Context)
#+end_src

* Vec__InterpAlias
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__InterpAlias
:group: Compiler tools
:END:

#+begin_src til
Vec__InterpAlias is a None
#+end_src

* Map__Str_HeapBinding
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding
:group: Compiler tools
:END:

#+begin_src til
struct Map__Str_HeapBinding {
    mut keys : Vec__Str
    mut values : Vec__HeapBinding
namespace:
    func new() returns Map__Str_HeapBinding
    func with_capacity(shallow n: USize) returns Map__Str_HeapBinding
    func len(self: Map__Str_HeapBinding) returns shallow USize
    func clear(mut self: Map__Str_HeapBinding)
    func has(self: Map__Str_HeapBinding, key: Str) returns shallow Bool
    func get(self: Map__Str_HeapBinding, key: Str, mut _err_kind: I64) returns ref HeapBinding
    func set(mut self: Map__Str_HeapBinding, key: Str, own val: HeapBinding)
    func remove(mut self: Map__Str_HeapBinding, key: Str) returns shallow Bool
    func delete(own self: Map__Str_HeapBinding, shallow call_free: Bool)
    func clone(self: Map__Str_HeapBinding) returns Map__Str_HeapBinding
    func size() returns shallow USize
    func hash(self: Map__Str_HeapBinding, hasher: HashFn) returns shallow U64
}
#+end_src

* Map__Str_HeapBinding.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding.new
:group: Compiler tools
:END:

Create an empty Map of the types provided for the key and values respectively.
The key type must implement ~cmp~.

#+begin_src til
func Map__Str_HeapBinding.new() returns Map__Str_HeapBinding
#+end_src

* Map__Str_HeapBinding.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding.with_capacity
:group: Compiler tools
:END:

Create an empty Map pre-sized for ~n~ entries, so inserting up to
~n~ reallocs neither backing Vec (Vec.with_capacity's
counterpart). n=0 behaves like new(): lazy-empty, no allocation.

#+begin_src til
func Map__Str_HeapBinding.with_capacity(shallow n: USize) returns Map__Str_HeapBinding
#+end_src

* Map__Str_HeapBinding.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding.clear
:group: Compiler tools
:END:

Drop all live keys and values but keep the allocated storage so the Map can be reused.

#+begin_src til
func Map__Str_HeapBinding.clear(mut self: Map__Str_HeapBinding)
#+end_src

* Map__Str_HeapBinding.has
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding.has
:group: Compiler tools
:END:

True if a value exists for the given key.

#+begin_src til
func Map__Str_HeapBinding.has(self: Map__Str_HeapBinding, key: Str) returns shallow Bool
#+end_src

* Map__Str_HeapBinding.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding.get
:group: Compiler tools
:END:

Return a ref to the value for ~key~. Throws KeyNotFound if
~key~ is absent; call as ~map.get(k)!~ (or ~map[k]~) to panic
on a missing key.

#+begin_src til
func Map__Str_HeapBinding.get(self: Map__Str_HeapBinding, key: Str, mut _err_kind: I64) returns ref HeapBinding
#+end_src

* Map__Str_HeapBinding.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding.set
:group: Compiler tools
:END:

Insert or overwrite the value for ~key~. The value is owned.

#+begin_src til
func Map__Str_HeapBinding.set(mut self: Map__Str_HeapBinding, key: Str, own val: HeapBinding)
#+end_src

* Map__Str_HeapBinding.remove
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Map__Str_HeapBinding.remove
:group: Compiler tools
:END:

Remove ~key~, dropping its key and value. Returns false if absent.

#+begin_src til
func Map__Str_HeapBinding.remove(mut self: Map__Str_HeapBinding, key: Str) returns shallow Bool
#+end_src

* Option__ref_HeapBinding
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_HeapBinding
:group: Compiler tools
:END:

#+begin_src til
enum Option__ref_HeapBinding {
    None
    Some: HeapBinding
namespace:
    func is_some(shallow self: Option__ref_HeapBinding) returns shallow Bool
    func is_none(shallow self: Option__ref_HeapBinding) returns shallow Bool
    func unwrap_or(self: Option__ref_HeapBinding, default_v: HeapBinding) returns ref HeapBinding
    func unwrap(self: Option__ref_HeapBinding) returns ref HeapBinding
    func take(own self: Option__ref_HeapBinding) returns ref HeapBinding
    ext_func None() returns shallow Option__ref_HeapBinding
    ext_func Some(val: HeapBinding) returns shallow Option__ref_HeapBinding
    core_func is(self: Option__ref_HeapBinding, other: Option__ref_HeapBinding) returns shallow Bool
    func delete(own self: Option__ref_HeapBinding, shallow call_free: Bool)
    func clone(self: Option__ref_HeapBinding) returns shallow Option__ref_HeapBinding
    func size() returns shallow USize
}
#+end_src

* Option__ref_HeapBinding.unwrap
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_HeapBinding.unwrap
:group: Compiler tools
:END:

The contained value; PANICS on None, ala Rust's unwrap. For the
~if o.is_none() { ... }~ + ~o.unwrap()~ idiom, where the caller
has already handled absence and unwrapping cannot fail. Prefer
a ~switch~ when both arms do real work, and ~unwrap_or~ when a
default is meaningful -- reach for this only when None is
unreachable by construction, so it fails loudly if that ever
stops being true.

#+begin_src til
func Option__ref_HeapBinding.unwrap(self: Option__ref_HeapBinding) returns ref HeapBinding
#+end_src

* Option__ref_HeapBinding.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_HeapBinding.take
:group: Compiler tools
:END:

The contained value, MOVED out; PANICS on None, like unwrap.
unwrap only BORROWS self, so for an owned payload it must hand
back a deep clone; this consumes the Option instead, so the
payload's bytes move and only the enum shell is freed (#321).
Use it wherever the caller takes ownership of what the Option
held -- an ~Option(Expr)~ returned by an AST helper, say, where
a clone would copy a whole subtree and break node identity.

#+begin_src til
func Option__ref_HeapBinding.take(own self: Option__ref_HeapBinding) returns ref HeapBinding
#+end_src

* Option__ref_Dynamic
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_Dynamic
:group: Compiler tools
:END:

#+begin_src til
enum Option__ref_Dynamic {
    None
    Some: Dynamic
namespace:
    func is_some(shallow self: Option__ref_Dynamic) returns shallow Bool
    func is_none(shallow self: Option__ref_Dynamic) returns shallow Bool
    func unwrap_or(self: Option__ref_Dynamic, default_v: Dynamic) returns ref Dynamic
    func unwrap(self: Option__ref_Dynamic) returns ref Dynamic
    func take(own self: Option__ref_Dynamic) returns ref Dynamic
    ext_func None() returns shallow Option__ref_Dynamic
    ext_func Some(val: Dynamic) returns shallow Option__ref_Dynamic
    core_func is(self: Option__ref_Dynamic, other: Option__ref_Dynamic) returns shallow Bool
    func delete(own self: Option__ref_Dynamic, shallow call_free: Bool)
    func clone(self: Option__ref_Dynamic) returns shallow Option__ref_Dynamic
    func size() returns shallow USize
}
#+end_src

* Option__ref_Dynamic.unwrap
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_Dynamic.unwrap
:group: Compiler tools
:END:

The contained value; PANICS on None, ala Rust's unwrap. For the
~if o.is_none() { ... }~ + ~o.unwrap()~ idiom, where the caller
has already handled absence and unwrapping cannot fail. Prefer
a ~switch~ when both arms do real work, and ~unwrap_or~ when a
default is meaningful -- reach for this only when None is
unreachable by construction, so it fails loudly if that ever
stops being true.

#+begin_src til
func Option__ref_Dynamic.unwrap(self: Option__ref_Dynamic) returns ref Dynamic
#+end_src

* Option__ref_Dynamic.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_Dynamic.take
:group: Compiler tools
:END:

The contained value, MOVED out; PANICS on None, like unwrap.
unwrap only BORROWS self, so for an owned payload it must hand
back a deep clone; this consumes the Option instead, so the
payload's bytes move and only the enum shell is freed (#321).
Use it wherever the caller takes ownership of what the Option
held -- an ~Option(Expr)~ returned by an AST helper, say, where
a clone would copy a whole subtree and break node identity.

#+begin_src til
func Option__ref_Dynamic.take(own self: Option__ref_Dynamic) returns ref Dynamic
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox
:group: Compiler tools
:END:

#+begin_src til
struct Vec__priv___src_self_interpreter_til__DynPtrBox {
    own mut data : U8
    mut count : USize
    mut cap : USize
namespace:
    func new() returns Vec__priv___src_self_interpreter_til__DynPtrBox
    func with_capacity(shallow n: USize) returns Vec__priv___src_self_interpreter_til__DynPtrBox
    func len(self: Vec__priv___src_self_interpreter_til__DynPtrBox) returns shallow USize
    func clear(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox)
    func delete_marked(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, marks: Dynamic)
    func push(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, own val: priv___src_self_interpreter_til__DynPtrBox)
    func append(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, own other: Vec__priv___src_self_interpreter_til__DynPtrBox)
    func take(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox) returns Vec__priv___src_self_interpreter_til__DynPtrBox
    func move_to(own self: Vec__priv___src_self_interpreter_til__DynPtrBox, mut dest: Vec__priv___src_self_interpreter_til__DynPtrBox)
    func move_from(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, own other: Vec__priv___src_self_interpreter_til__DynPtrBox)
    func unsafe_get(self: Vec__priv___src_self_interpreter_til__DynPtrBox, i: USize) returns ref priv___src_self_interpreter_til__DynPtrBox
    func get(self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_interpreter_til__DynPtrBox
    func pop(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox) returns priv___src_self_interpreter_til__DynPtrBox
    func remove_at(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, mut _err_kind: I64)
    func take_prefix(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow n: USize) returns Vec__priv___src_self_interpreter_til__DynPtrBox
    func truncate(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow n: USize)
    func unsafe_set(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, own val: priv___src_self_interpreter_til__DynPtrBox)
    func set(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, own val: priv___src_self_interpreter_til__DynPtrBox, mut _err_kind: I64)
    func push_take(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, mut src: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize)
    func delete(own self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow call_free: Bool)
    func clone(self: Vec__priv___src_self_interpreter_til__DynPtrBox) returns Vec__priv___src_self_interpreter_til__DynPtrBox
    func size() returns shallow USize
}
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.new
:group: Compiler tools
:END:

Create a new empty Vec for elements of type T. Lazy: no allocation
until the first push -- an empty Vec is (data=NULL, count=0, cap=0),
and the grow sites below seed cap 0->1 on the first insert. This keeps
the many containers that stay empty (e.g. the unused maps in a fresh
Scope) allocation-free, which is the dominant per-call interpreter cost.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.new() returns Vec__priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.with_capacity
:group: Compiler tools
:END:

Create an empty Vec pre-sized for ~n~ elements, so pushing up to ~n~
items reallocs zero times. Use at call sites where the final length is
known up front (cloning a Vec of known length, building a fixed arg
list, ...) to avoid the 1->2->4->...->n grow-and-realloc churn that
~new()~ + repeated ~push~ pays. n=0 behaves like new(): lazy-empty,
no allocation (the grow sites seed cap 0->1 on the first insert).

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.with_capacity(shallow n: USize) returns Vec__priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.clear
:group: Compiler tools
:END:

Drop all live elements via elem_delete but keep the allocated
storage and element-type metadata so the Vec can be reused.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.clear(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.delete_marked
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.delete_marked
:group: Compiler tools
:END:

Drop the elements flagged in ~marks~ (a byte-per-element buffer,
nonzero = drop, at least self.count entries) via elem_delete, then
compact the survivors forward and update count. This is the
container home for the scavenger's mark/sweep/compact, which used
to reach into data/count directly.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.delete_marked(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, marks: Dynamic)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.push
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.push
:group: Compiler tools
:END:

Append an element to the end. ~val~ is owned: after this call the
caller must not use the value passed -- clone it first if needed.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.push(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, own val: priv___src_self_interpreter_til__DynPtrBox)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.append
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.append
:group: Compiler tools
:END:

Consume the contents of ~other~ by appending them to ~self~.
~other~ is taken by ownership and will be empty after the call.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.append(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, own other: Vec__priv___src_self_interpreter_til__DynPtrBox)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.take
:group: Compiler tools
:END:

Take the contents out: the returned Vec owns self's buffer and
self is left lazy-empty. No element is copied or cloned.

This is how a struct FIELD hands its contents over
(~mut old := body.children.take()~): a field cannot be an ~own~
argument or receiver, because the callee would then free the
ADDRESS OF THE FIELD -- the compiler dies with "free(): invalid
pointer" compiling itself. Everything the caller can give away
uses the two move forms below instead.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.take(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox) returns Vec__priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.move_to
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.move_to
:group: Compiler tools
:END:

Give self's contents to ~dest~, which drops whatever it held.
SELF is consumed, so the receiver is the owned one and the call
spells the type out: ~Vec(T).move_to(own src, dest)~.

The three fields move as BYTES on purpose:
~dest.data = self.data~ drops dest's old pointer (right) and then
~self.data = 0~ drops the pointer dest just adopted -- a double
free, which is what the emitted C does with field assignment.
Blanking the source leaves a genuinely valid lazy-empty Vec, so
a later push on it allocates afresh instead of reallocating a
buffer that now belongs to someone else.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.move_to(own self: Vec__priv___src_self_interpreter_til__DynPtrBox, mut dest: Vec__priv___src_self_interpreter_til__DynPtrBox)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.move_from
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.move_from
:group: Compiler tools
:END:

Take ~other~'s contents, dropping whatever self held. OTHER is
consumed -- it is the value being emptied, so it is the owned
argument: ~dest.move_from(own src)~.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.move_from(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, own other: Vec__priv___src_self_interpreter_til__DynPtrBox)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.unsafe_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.unsafe_get
:group: Compiler tools
:END:

Unchecked element access: return a reference to the element at
index ~i~ with NO bounds check. The caller must prove ~i < len()~.
This is the unchecked core that ~get~ wraps; for-in uses it
directly because its ~_fi < len()~ termination test already
proves the index in bounds (issue #284).

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.unsafe_get(self: Vec__priv___src_self_interpreter_til__DynPtrBox, i: USize) returns ref priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.get
:group: Compiler tools
:END:

Return a reference to the element at index ~i~. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i]~
to panic on a bad index. The reference is valid until the
next mutation.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.get(self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.pop
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.pop
:group: Compiler tools
:END:

Remove and return the last element. Panics if empty. The caller
takes ownership of the returned value.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.pop(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox) returns priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.remove_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.remove_at
:group: Compiler tools
:END:

Remove and drop the element at ~i~, shifting later elements left.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.remove_at(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, mut _err_kind: I64)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.take_prefix
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.take_prefix
:group: Compiler tools
:END:

Split off the first ~n~ elements into a new Vec. Panics if ~n~
exceeds self.len(). The remaining elements shift to the front.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.take_prefix(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow n: USize) returns Vec__priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.truncate
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.truncate
:group: Compiler tools
:END:

Drop the elements from index ~n~ to the end, freeing each via
elem_delete, and set count to ~n~ (the survivors [0, n) are left
untouched). Panics if ~n~ exceeds len. This is the container home
for a pop-and-free-the-tail loop shrinking a Vec back to a mark.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.truncate(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow n: USize)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.unsafe_set
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.unsafe_set
:group: Compiler tools
:END:

Overwrite the element at index ~i~ without a bounds check, dropping
the old value. Caller guarantees ~i < self.count~; the write-side
mirror of unsafe_get (issue #284).

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.unsafe_set(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, own val: priv___src_self_interpreter_til__DynPtrBox)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.set
:group: Compiler tools
:END:

Overwrite the element at index ~i~. ~val~ is owned. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i] = val~
(or ~vec.set(i, own val)!~) to panic on a bad index.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.set(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize, own val: priv___src_self_interpreter_til__DynPtrBox, mut _err_kind: I64)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.push_take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.push_take
:group: Compiler tools
:END:

Move bytes of src[i] into self (push). Source slot is zeroed so that
src's eventual elem_delete on it is a no-op (relies on the same
count==0/data==NULL convention used by take_children and Vec.delete).

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.push_take(mut self: Vec__priv___src_self_interpreter_til__DynPtrBox, mut src: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow i: USize)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.delete
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.delete
:group: Compiler tools
:END:

Drop each element via elem_delete, free storage, then free self
unless ~call_free~ is false.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.delete(own self: Vec__priv___src_self_interpreter_til__DynPtrBox, shallow call_free: Bool)
#+end_src

* Vec__priv___src_self_interpreter_til__DynPtrBox.clone
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__DynPtrBox.clone
:group: Compiler tools
:END:

Deep-copy the Vec and all its elements via elem_clone.

#+begin_src til
func Vec__priv___src_self_interpreter_til__DynPtrBox.clone(self: Vec__priv___src_self_interpreter_til__DynPtrBox) returns Vec__priv___src_self_interpreter_til__DynPtrBox
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias
:group: Compiler tools
:END:

#+begin_src til
struct Vec__priv___src_self_interpreter_til__InterpAlias {
    own mut data : U8
    mut count : USize
    mut cap : USize
namespace:
    func new() returns Vec__priv___src_self_interpreter_til__InterpAlias
    func with_capacity(shallow n: USize) returns Vec__priv___src_self_interpreter_til__InterpAlias
    func len(self: Vec__priv___src_self_interpreter_til__InterpAlias) returns shallow USize
    func clear(mut self: Vec__priv___src_self_interpreter_til__InterpAlias)
    func delete_marked(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, marks: Dynamic)
    func push(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, own val: priv___src_self_interpreter_til__InterpAlias)
    func append(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, own other: Vec__priv___src_self_interpreter_til__InterpAlias)
    func take(mut self: Vec__priv___src_self_interpreter_til__InterpAlias) returns Vec__priv___src_self_interpreter_til__InterpAlias
    func move_to(own self: Vec__priv___src_self_interpreter_til__InterpAlias, mut dest: Vec__priv___src_self_interpreter_til__InterpAlias)
    func move_from(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, own other: Vec__priv___src_self_interpreter_til__InterpAlias)
    func unsafe_get(self: Vec__priv___src_self_interpreter_til__InterpAlias, i: USize) returns ref priv___src_self_interpreter_til__InterpAlias
    func get(self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_interpreter_til__InterpAlias
    func pop(mut self: Vec__priv___src_self_interpreter_til__InterpAlias) returns priv___src_self_interpreter_til__InterpAlias
    func remove_at(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, mut _err_kind: I64)
    func take_prefix(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow n: USize) returns Vec__priv___src_self_interpreter_til__InterpAlias
    func truncate(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow n: USize)
    func unsafe_set(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, own val: priv___src_self_interpreter_til__InterpAlias)
    func set(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, own val: priv___src_self_interpreter_til__InterpAlias, mut _err_kind: I64)
    func push_take(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, mut src: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize)
    func delete(own self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow call_free: Bool)
    func clone(self: Vec__priv___src_self_interpreter_til__InterpAlias) returns Vec__priv___src_self_interpreter_til__InterpAlias
    func size() returns shallow USize
}
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.new
:group: Compiler tools
:END:

Create a new empty Vec for elements of type T. Lazy: no allocation
until the first push -- an empty Vec is (data=NULL, count=0, cap=0),
and the grow sites below seed cap 0->1 on the first insert. This keeps
the many containers that stay empty (e.g. the unused maps in a fresh
Scope) allocation-free, which is the dominant per-call interpreter cost.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.new() returns Vec__priv___src_self_interpreter_til__InterpAlias
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.with_capacity
:group: Compiler tools
:END:

Create an empty Vec pre-sized for ~n~ elements, so pushing up to ~n~
items reallocs zero times. Use at call sites where the final length is
known up front (cloning a Vec of known length, building a fixed arg
list, ...) to avoid the 1->2->4->...->n grow-and-realloc churn that
~new()~ + repeated ~push~ pays. n=0 behaves like new(): lazy-empty,
no allocation (the grow sites seed cap 0->1 on the first insert).

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.with_capacity(shallow n: USize) returns Vec__priv___src_self_interpreter_til__InterpAlias
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.clear
:group: Compiler tools
:END:

Drop all live elements via elem_delete but keep the allocated
storage and element-type metadata so the Vec can be reused.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.clear(mut self: Vec__priv___src_self_interpreter_til__InterpAlias)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.delete_marked
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.delete_marked
:group: Compiler tools
:END:

Drop the elements flagged in ~marks~ (a byte-per-element buffer,
nonzero = drop, at least self.count entries) via elem_delete, then
compact the survivors forward and update count. This is the
container home for the scavenger's mark/sweep/compact, which used
to reach into data/count directly.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.delete_marked(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, marks: Dynamic)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.push
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.push
:group: Compiler tools
:END:

Append an element to the end. ~val~ is owned: after this call the
caller must not use the value passed -- clone it first if needed.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.push(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, own val: priv___src_self_interpreter_til__InterpAlias)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.append
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.append
:group: Compiler tools
:END:

Consume the contents of ~other~ by appending them to ~self~.
~other~ is taken by ownership and will be empty after the call.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.append(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, own other: Vec__priv___src_self_interpreter_til__InterpAlias)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.take
:group: Compiler tools
:END:

Take the contents out: the returned Vec owns self's buffer and
self is left lazy-empty. No element is copied or cloned.

This is how a struct FIELD hands its contents over
(~mut old := body.children.take()~): a field cannot be an ~own~
argument or receiver, because the callee would then free the
ADDRESS OF THE FIELD -- the compiler dies with "free(): invalid
pointer" compiling itself. Everything the caller can give away
uses the two move forms below instead.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.take(mut self: Vec__priv___src_self_interpreter_til__InterpAlias) returns Vec__priv___src_self_interpreter_til__InterpAlias
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.move_to
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.move_to
:group: Compiler tools
:END:

Give self's contents to ~dest~, which drops whatever it held.
SELF is consumed, so the receiver is the owned one and the call
spells the type out: ~Vec(T).move_to(own src, dest)~.

The three fields move as BYTES on purpose:
~dest.data = self.data~ drops dest's old pointer (right) and then
~self.data = 0~ drops the pointer dest just adopted -- a double
free, which is what the emitted C does with field assignment.
Blanking the source leaves a genuinely valid lazy-empty Vec, so
a later push on it allocates afresh instead of reallocating a
buffer that now belongs to someone else.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.move_to(own self: Vec__priv___src_self_interpreter_til__InterpAlias, mut dest: Vec__priv___src_self_interpreter_til__InterpAlias)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.move_from
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.move_from
:group: Compiler tools
:END:

Take ~other~'s contents, dropping whatever self held. OTHER is
consumed -- it is the value being emptied, so it is the owned
argument: ~dest.move_from(own src)~.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.move_from(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, own other: Vec__priv___src_self_interpreter_til__InterpAlias)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.unsafe_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.unsafe_get
:group: Compiler tools
:END:

Unchecked element access: return a reference to the element at
index ~i~ with NO bounds check. The caller must prove ~i < len()~.
This is the unchecked core that ~get~ wraps; for-in uses it
directly because its ~_fi < len()~ termination test already
proves the index in bounds (issue #284).

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.unsafe_get(self: Vec__priv___src_self_interpreter_til__InterpAlias, i: USize) returns ref priv___src_self_interpreter_til__InterpAlias
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.get
:group: Compiler tools
:END:

Return a reference to the element at index ~i~. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i]~
to panic on a bad index. The reference is valid until the
next mutation.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.get(self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_interpreter_til__InterpAlias
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.pop
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.pop
:group: Compiler tools
:END:

Remove and return the last element. Panics if empty. The caller
takes ownership of the returned value.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.pop(mut self: Vec__priv___src_self_interpreter_til__InterpAlias) returns priv___src_self_interpreter_til__InterpAlias
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.remove_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.remove_at
:group: Compiler tools
:END:

Remove and drop the element at ~i~, shifting later elements left.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.remove_at(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, mut _err_kind: I64)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.take_prefix
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.take_prefix
:group: Compiler tools
:END:

Split off the first ~n~ elements into a new Vec. Panics if ~n~
exceeds self.len(). The remaining elements shift to the front.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.take_prefix(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow n: USize) returns Vec__priv___src_self_interpreter_til__InterpAlias
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.truncate
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.truncate
:group: Compiler tools
:END:

Drop the elements from index ~n~ to the end, freeing each via
elem_delete, and set count to ~n~ (the survivors [0, n) are left
untouched). Panics if ~n~ exceeds len. This is the container home
for a pop-and-free-the-tail loop shrinking a Vec back to a mark.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.truncate(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow n: USize)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.unsafe_set
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.unsafe_set
:group: Compiler tools
:END:

Overwrite the element at index ~i~ without a bounds check, dropping
the old value. Caller guarantees ~i < self.count~; the write-side
mirror of unsafe_get (issue #284).

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.unsafe_set(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, own val: priv___src_self_interpreter_til__InterpAlias)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.set
:group: Compiler tools
:END:

Overwrite the element at index ~i~. ~val~ is owned. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i] = val~
(or ~vec.set(i, own val)!~) to panic on a bad index.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.set(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize, own val: priv___src_self_interpreter_til__InterpAlias, mut _err_kind: I64)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.push_take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.push_take
:group: Compiler tools
:END:

Move bytes of src[i] into self (push). Source slot is zeroed so that
src's eventual elem_delete on it is a no-op (relies on the same
count==0/data==NULL convention used by take_children and Vec.delete).

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.push_take(mut self: Vec__priv___src_self_interpreter_til__InterpAlias, mut src: Vec__priv___src_self_interpreter_til__InterpAlias, shallow i: USize)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.delete
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.delete
:group: Compiler tools
:END:

Drop each element via elem_delete, free storage, then free self
unless ~call_free~ is false.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.delete(own self: Vec__priv___src_self_interpreter_til__InterpAlias, shallow call_free: Bool)
#+end_src

* Vec__priv___src_self_interpreter_til__InterpAlias.clone
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__priv___src_self_interpreter_til__InterpAlias.clone
:group: Compiler tools
:END:

Deep-copy the Vec and all its elements via elem_clone.

#+begin_src til
func Vec__priv___src_self_interpreter_til__InterpAlias.clone(self: Vec__priv___src_self_interpreter_til__InterpAlias) returns Vec__priv___src_self_interpreter_til__InterpAlias
#+end_src

* Option__ref_ffi_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_ffi_type
:group: Compiler tools
:END:

#+begin_src til
enum Option__ref_ffi_type {
    None
    Some: ffi_type
namespace:
    func is_some(shallow self: Option__ref_ffi_type) returns shallow Bool
    func is_none(shallow self: Option__ref_ffi_type) returns shallow Bool
    func unwrap_or(self: Option__ref_ffi_type, default_v: ffi_type) returns ref ffi_type
    func unwrap(self: Option__ref_ffi_type) returns ref ffi_type
    func take(own self: Option__ref_ffi_type) returns ref ffi_type
    ext_func None() returns shallow Option__ref_ffi_type
    ext_func Some(val: ffi_type) returns shallow Option__ref_ffi_type
    core_func is(self: Option__ref_ffi_type, other: Option__ref_ffi_type) returns shallow Bool
    func delete(own self: Option__ref_ffi_type, shallow call_free: Bool)
    func clone(self: Option__ref_ffi_type) returns shallow Option__ref_ffi_type
    func size() returns shallow USize
}
#+end_src

* Option__ref_ffi_type.unwrap
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_ffi_type.unwrap
:group: Compiler tools
:END:

The contained value; PANICS on None, ala Rust's unwrap. For the
~if o.is_none() { ... }~ + ~o.unwrap()~ idiom, where the caller
has already handled absence and unwrapping cannot fail. Prefer
a ~switch~ when both arms do real work, and ~unwrap_or~ when a
default is meaningful -- reach for this only when None is
unreachable by construction, so it fails loudly if that ever
stops being true.

#+begin_src til
func Option__ref_ffi_type.unwrap(self: Option__ref_ffi_type) returns ref ffi_type
#+end_src

* Option__ref_ffi_type.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Option__ref_ffi_type.take
:group: Compiler tools
:END:

The contained value, MOVED out; PANICS on None, like unwrap.
unwrap only BORROWS self, so for an owned payload it must hand
back a deep clone; this consumes the Option instead, so the
payload's bytes move and only the enum shell is freed (#321).
Use it wherever the caller takes ownership of what the Option
held -- an ~Option(Expr)~ returned by an AST helper, say, where
a clone would copy a whole subtree and break node identity.

#+begin_src til
func Option__ref_ffi_type.take(own self: Option__ref_ffi_type) returns ref ffi_type
#+end_src

* Vec__HeapBinding
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding
:group: Compiler tools
:END:

#+begin_src til
struct Vec__HeapBinding {
    own mut data : U8
    mut count : USize
    mut cap : USize
namespace:
    func new() returns Vec__HeapBinding
    func with_capacity(shallow n: USize) returns Vec__HeapBinding
    func len(self: Vec__HeapBinding) returns shallow USize
    func clear(mut self: Vec__HeapBinding)
    func delete_marked(mut self: Vec__HeapBinding, marks: Dynamic)
    func push(mut self: Vec__HeapBinding, own val: HeapBinding)
    func append(mut self: Vec__HeapBinding, own other: Vec__HeapBinding)
    func take(mut self: Vec__HeapBinding) returns Vec__HeapBinding
    func move_to(own self: Vec__HeapBinding, mut dest: Vec__HeapBinding)
    func move_from(mut self: Vec__HeapBinding, own other: Vec__HeapBinding)
    func unsafe_get(self: Vec__HeapBinding, i: USize) returns ref HeapBinding
    func get(self: Vec__HeapBinding, shallow i: USize, mut _err_kind: I64) returns ref HeapBinding
    func pop(mut self: Vec__HeapBinding) returns HeapBinding
    func remove_at(mut self: Vec__HeapBinding, shallow i: USize, mut _err_kind: I64)
    func take_prefix(mut self: Vec__HeapBinding, shallow n: USize) returns Vec__HeapBinding
    func truncate(mut self: Vec__HeapBinding, shallow n: USize)
    func unsafe_set(mut self: Vec__HeapBinding, shallow i: USize, own val: HeapBinding)
    func set(mut self: Vec__HeapBinding, shallow i: USize, own val: HeapBinding, mut _err_kind: I64)
    func push_take(mut self: Vec__HeapBinding, mut src: Vec__HeapBinding, shallow i: USize)
    func delete(own self: Vec__HeapBinding, shallow call_free: Bool)
    func clone(self: Vec__HeapBinding) returns Vec__HeapBinding
    func size() returns shallow USize
}
#+end_src

* Vec__HeapBinding.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.new
:group: Compiler tools
:END:

Create a new empty Vec for elements of type T. Lazy: no allocation
until the first push -- an empty Vec is (data=NULL, count=0, cap=0),
and the grow sites below seed cap 0->1 on the first insert. This keeps
the many containers that stay empty (e.g. the unused maps in a fresh
Scope) allocation-free, which is the dominant per-call interpreter cost.

#+begin_src til
func Vec__HeapBinding.new() returns Vec__HeapBinding
#+end_src

* Vec__HeapBinding.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.with_capacity
:group: Compiler tools
:END:

Create an empty Vec pre-sized for ~n~ elements, so pushing up to ~n~
items reallocs zero times. Use at call sites where the final length is
known up front (cloning a Vec of known length, building a fixed arg
list, ...) to avoid the 1->2->4->...->n grow-and-realloc churn that
~new()~ + repeated ~push~ pays. n=0 behaves like new(): lazy-empty,
no allocation (the grow sites seed cap 0->1 on the first insert).

#+begin_src til
func Vec__HeapBinding.with_capacity(shallow n: USize) returns Vec__HeapBinding
#+end_src

* Vec__HeapBinding.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.clear
:group: Compiler tools
:END:

Drop all live elements via elem_delete but keep the allocated
storage and element-type metadata so the Vec can be reused.

#+begin_src til
func Vec__HeapBinding.clear(mut self: Vec__HeapBinding)
#+end_src

* Vec__HeapBinding.delete_marked
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.delete_marked
:group: Compiler tools
:END:

Drop the elements flagged in ~marks~ (a byte-per-element buffer,
nonzero = drop, at least self.count entries) via elem_delete, then
compact the survivors forward and update count. This is the
container home for the scavenger's mark/sweep/compact, which used
to reach into data/count directly.

#+begin_src til
func Vec__HeapBinding.delete_marked(mut self: Vec__HeapBinding, marks: Dynamic)
#+end_src

* Vec__HeapBinding.push
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.push
:group: Compiler tools
:END:

Append an element to the end. ~val~ is owned: after this call the
caller must not use the value passed -- clone it first if needed.

#+begin_src til
func Vec__HeapBinding.push(mut self: Vec__HeapBinding, own val: HeapBinding)
#+end_src

* Vec__HeapBinding.append
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.append
:group: Compiler tools
:END:

Consume the contents of ~other~ by appending them to ~self~.
~other~ is taken by ownership and will be empty after the call.

#+begin_src til
func Vec__HeapBinding.append(mut self: Vec__HeapBinding, own other: Vec__HeapBinding)
#+end_src

* Vec__HeapBinding.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.take
:group: Compiler tools
:END:

Take the contents out: the returned Vec owns self's buffer and
self is left lazy-empty. No element is copied or cloned.

This is how a struct FIELD hands its contents over
(~mut old := body.children.take()~): a field cannot be an ~own~
argument or receiver, because the callee would then free the
ADDRESS OF THE FIELD -- the compiler dies with "free(): invalid
pointer" compiling itself. Everything the caller can give away
uses the two move forms below instead.

#+begin_src til
func Vec__HeapBinding.take(mut self: Vec__HeapBinding) returns Vec__HeapBinding
#+end_src

* Vec__HeapBinding.move_to
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.move_to
:group: Compiler tools
:END:

Give self's contents to ~dest~, which drops whatever it held.
SELF is consumed, so the receiver is the owned one and the call
spells the type out: ~Vec(T).move_to(own src, dest)~.

The three fields move as BYTES on purpose:
~dest.data = self.data~ drops dest's old pointer (right) and then
~self.data = 0~ drops the pointer dest just adopted -- a double
free, which is what the emitted C does with field assignment.
Blanking the source leaves a genuinely valid lazy-empty Vec, so
a later push on it allocates afresh instead of reallocating a
buffer that now belongs to someone else.

#+begin_src til
func Vec__HeapBinding.move_to(own self: Vec__HeapBinding, mut dest: Vec__HeapBinding)
#+end_src

* Vec__HeapBinding.move_from
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.move_from
:group: Compiler tools
:END:

Take ~other~'s contents, dropping whatever self held. OTHER is
consumed -- it is the value being emptied, so it is the owned
argument: ~dest.move_from(own src)~.

#+begin_src til
func Vec__HeapBinding.move_from(mut self: Vec__HeapBinding, own other: Vec__HeapBinding)
#+end_src

* Vec__HeapBinding.unsafe_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.unsafe_get
:group: Compiler tools
:END:

Unchecked element access: return a reference to the element at
index ~i~ with NO bounds check. The caller must prove ~i < len()~.
This is the unchecked core that ~get~ wraps; for-in uses it
directly because its ~_fi < len()~ termination test already
proves the index in bounds (issue #284).

#+begin_src til
func Vec__HeapBinding.unsafe_get(self: Vec__HeapBinding, i: USize) returns ref HeapBinding
#+end_src

* Vec__HeapBinding.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.get
:group: Compiler tools
:END:

Return a reference to the element at index ~i~. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i]~
to panic on a bad index. The reference is valid until the
next mutation.

#+begin_src til
func Vec__HeapBinding.get(self: Vec__HeapBinding, shallow i: USize, mut _err_kind: I64) returns ref HeapBinding
#+end_src

* Vec__HeapBinding.pop
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.pop
:group: Compiler tools
:END:

Remove and return the last element. Panics if empty. The caller
takes ownership of the returned value.

#+begin_src til
func Vec__HeapBinding.pop(mut self: Vec__HeapBinding) returns HeapBinding
#+end_src

* Vec__HeapBinding.remove_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.remove_at
:group: Compiler tools
:END:

Remove and drop the element at ~i~, shifting later elements left.

#+begin_src til
func Vec__HeapBinding.remove_at(mut self: Vec__HeapBinding, shallow i: USize, mut _err_kind: I64)
#+end_src

* Vec__HeapBinding.take_prefix
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.take_prefix
:group: Compiler tools
:END:

Split off the first ~n~ elements into a new Vec. Panics if ~n~
exceeds self.len(). The remaining elements shift to the front.

#+begin_src til
func Vec__HeapBinding.take_prefix(mut self: Vec__HeapBinding, shallow n: USize) returns Vec__HeapBinding
#+end_src

* Vec__HeapBinding.truncate
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.truncate
:group: Compiler tools
:END:

Drop the elements from index ~n~ to the end, freeing each via
elem_delete, and set count to ~n~ (the survivors [0, n) are left
untouched). Panics if ~n~ exceeds len. This is the container home
for a pop-and-free-the-tail loop shrinking a Vec back to a mark.

#+begin_src til
func Vec__HeapBinding.truncate(mut self: Vec__HeapBinding, shallow n: USize)
#+end_src

* Vec__HeapBinding.unsafe_set
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.unsafe_set
:group: Compiler tools
:END:

Overwrite the element at index ~i~ without a bounds check, dropping
the old value. Caller guarantees ~i < self.count~; the write-side
mirror of unsafe_get (issue #284).

#+begin_src til
func Vec__HeapBinding.unsafe_set(mut self: Vec__HeapBinding, shallow i: USize, own val: HeapBinding)
#+end_src

* Vec__HeapBinding.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.set
:group: Compiler tools
:END:

Overwrite the element at index ~i~. ~val~ is owned. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i] = val~
(or ~vec.set(i, own val)!~) to panic on a bad index.

#+begin_src til
func Vec__HeapBinding.set(mut self: Vec__HeapBinding, shallow i: USize, own val: HeapBinding, mut _err_kind: I64)
#+end_src

* Vec__HeapBinding.push_take
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.push_take
:group: Compiler tools
:END:

Move bytes of src[i] into self (push). Source slot is zeroed so that
src's eventual elem_delete on it is a no-op (relies on the same
count==0/data==NULL convention used by take_children and Vec.delete).

#+begin_src til
func Vec__HeapBinding.push_take(mut self: Vec__HeapBinding, mut src: Vec__HeapBinding, shallow i: USize)
#+end_src

* Vec__HeapBinding.delete
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.delete
:group: Compiler tools
:END:

Drop each element via elem_delete, free storage, then free self
unless ~call_free~ is false.

#+begin_src til
func Vec__HeapBinding.delete(own self: Vec__HeapBinding, shallow call_free: Bool)
#+end_src

* Vec__HeapBinding.clone
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.Vec__HeapBinding.clone
:group: Compiler tools
:END:

Deep-copy the Vec and all its elements via elem_clone.

#+begin_src til
func Vec__HeapBinding.clone(self: Vec__HeapBinding) returns Vec__HeapBinding
#+end_src

* adopt__HeapBinding
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.adopt__HeapBinding
:group: Compiler tools
:END:

#+begin_src til
func adopt__HeapBinding(mut dest: Dynamic, own src: HeapBinding)
#+end_src

* adopt__priv___src_self_interpreter_til__DynPtrBox
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.adopt__priv___src_self_interpreter_til__DynPtrBox
:group: Compiler tools
:END:

#+begin_src til
func adopt__priv___src_self_interpreter_til__DynPtrBox(mut dest: Dynamic, own src: priv___src_self_interpreter_til__DynPtrBox)
#+end_src

* adopt__priv___src_self_interpreter_til__InterpAlias
:PROPERTIES:
:CUSTOM_ID: til.src.self.interpreter.adopt__priv___src_self_interpreter_til__InterpAlias
:group: Compiler tools
:END:

#+begin_src til
func adopt__priv___src_self_interpreter_til__InterpAlias(mut dest: Dynamic, own src: priv___src_self_interpreter_til__InterpAlias)
#+end_src
