#+TITLE: src/self/typer.til
#+SUBTITLE: til 0.0.1-0c9fbc0e4
#+OPTIONS: toc:t

* fa_is_ns
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fa_is_ns
:group: Compiler frontend
:END:

#+begin_src til
func fa_is_ns(e: Expr, scope: TypeScope) returns shallow Bool
#+end_src

* make_til_type_expr
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.make_til_type_expr
:group: Compiler frontend
:END:

#+begin_src til
func make_til_type_expr(src: Expr, t: Type) returns Expr
#+end_src

* fa_own_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fa_own_type
:group: Compiler frontend
:END:

#+begin_src til
func fa_own_type(e: Expr, scope: TypeScope) returns shallow OwnType
#+end_src

* I64Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.I64Name
:group: Compiler frontend
:END:

#+begin_src til
I64Name is a Str
#+end_src

* U8Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.U8Name
:group: Compiler frontend
:END:

#+begin_src til
U8Name is a Str
#+end_src

* I8Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.I8Name
:group: Compiler frontend
:END:

#+begin_src til
I8Name is a Str
#+end_src

* I16Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.I16Name
:group: Compiler frontend
:END:

#+begin_src til
I16Name is a Str
#+end_src

* U16Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.U16Name
:group: Compiler frontend
:END:

#+begin_src til
U16Name is a Str
#+end_src

* I32Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.I32Name
:group: Compiler frontend
:END:

#+begin_src til
I32Name is a Str
#+end_src

* U32Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.U32Name
:group: Compiler frontend
:END:

#+begin_src til
U32Name is a Str
#+end_src

* U64Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.U64Name
:group: Compiler frontend
:END:

#+begin_src til
U64Name is a Str
#+end_src

* F32Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.F32Name
:group: Compiler frontend
:END:

#+begin_src til
F32Name is a Str
#+end_src

* F64Name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.F64Name
:group: Compiler frontend
:END:

#+begin_src til
F64Name is a Str
#+end_src

* BoolName
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.BoolName
:group: Compiler frontend
:END:

#+begin_src til
BoolName is a Str
#+end_src

* type_error
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_error
:group: Compiler frontend
:END:

#+begin_src til
proc type_error(e: Expr, msg: Str, mut ctx: Context)
#+end_src

* type_error_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_error_at
:group: Compiler frontend
:END:

#+begin_src til
proc type_error_at(path: Str, shallow line: U32, shallow col: U32, msg: Str, mut ctx: Context)
#+end_src

* find_namespace_func
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.find_namespace_func
:group: Compiler frontend
:END:

#+begin_src til
func find_namespace_func(sdef: Expr, method: Str, scope: TypeScope) returns shallow Option__ref_Expr
#+end_src

* find_ns_decl
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.find_ns_decl
:group: Compiler frontend
:END:

#+begin_src til
func find_ns_decl(sdef: Expr, method: Str) returns shallow Option__ref_Declaration
#+end_src

* resolve_fn_sig
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.resolve_fn_sig
:group: Compiler frontend
:END:

#+begin_src til
func resolve_fn_sig(fcall: Expr, scope: TypeScope) returns shallow Option__ref_Expr
#+end_src

* fcall_returns_own
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fcall_returns_own
:group: Compiler frontend
:END:

#+begin_src til
func fcall_returns_own(fcall: Expr, scope: TypeScope) returns shallow Bool
#+end_src

* is_clone_fcall
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.is_clone_fcall
:group: Compiler frontend
:END:

#+begin_src til
func is_clone_fcall(e: Expr) returns shallow Bool
#+end_src

* resolve_default_value
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.resolve_default_value
:group: Compiler frontend
:END:

#+begin_src til
func resolve_default_value(default_value: Expr, call_expr: Expr, ctx: Context) returns Expr
#+end_src

* expr_declared_type_name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.expr_declared_type_name
:group: Compiler frontend
:END:

#+begin_src til
func expr_declared_type_name(scope: TypeScope, e: Expr) returns Str
#+end_src

* infer_expr
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.infer_expr
:group: Compiler frontend
:END:

#+begin_src til
proc infer_expr(mut scope: TypeScope, mut expr: Expr, shallow in_func: I32, mut ctx: Context)
#+end_src

* PTR_SIZE_BYTES
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.PTR_SIZE_BYTES
:group: Compiler frontend
:END:

#+begin_src til
PTR_SIZE_BYTES is a U32
#+end_src

* check_unused_locals
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.check_unused_locals
:group: Compiler frontend
:END:

#+begin_src til
proc check_unused_locals(scope: TypeScope, path: Str, mut ctx: Context)
#+end_src

* check_unused_mut_locals
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.check_unused_mut_locals
:group: Compiler frontend
:END:

#+begin_src til
proc check_unused_mut_locals(scope: TypeScope, path: Str, mut ctx: Context)
#+end_src

* mark_binding_referenced
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.mark_binding_referenced
:group: Compiler frontend
:END:

#+begin_src til
func mark_binding_referenced(mut ctx: Context, mut b: TypeBinding)
#+end_src

* check_unused_priv_top_level
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.check_unused_priv_top_level
:group: Compiler frontend
:END:

#+begin_src til
proc check_unused_priv_top_level(mut scope: TypeScope, mut ctx: Context) returns shallow I32
#+end_src

* check_unused_priv_members_in_program
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.check_unused_priv_members_in_program
:group: Compiler frontend
:END:

#+begin_src til
proc check_unused_priv_members_in_program(program: Expr, path: Str, mut ctx: Context) returns shallow I32
#+end_src

* is_simple_lvalue_expr
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.is_simple_lvalue_expr
:group: Compiler frontend
:END:

#+begin_src til
func is_simple_lvalue_expr(e: Expr) returns shallow Bool
#+end_src

* is_compile_directive
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.is_compile_directive
:group: Compiler frontend
:END:

#+begin_src til
func is_compile_directive(e: Expr) returns shallow Bool
#+end_src

* infer_body_stmt
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.infer_body_stmt
:group: Compiler frontend
:END:

#+begin_src til
proc infer_body_stmt(mut scope: TypeScope, mut body: Expr, mut i: USize, shallow in_func: I32, shallow in_loop: I32, shallow returns_ref: I32, shallow in_type_body: I32, mut ctx: Context)
#+end_src

* reregister_repl_scope_defs
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.reregister_repl_scope_defs
:group: Compiler frontend
:END:

#+begin_src til
func reregister_repl_scope_defs(body: Expr, mut scope: TypeScope)
#+end_src

* infer_body
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.infer_body
:group: Compiler frontend
:END:

#+begin_src til
proc infer_body(mut scope: TypeScope, mut body: Expr, shallow in_func: I32, shallow owns_scope: I32, shallow in_loop: I32, shallow returns_ref: I32, shallow in_type_body: I32, mut ctx: Context)
#+end_src

* normalize_scope_bindings
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.normalize_scope_bindings
:group: Compiler frontend
:END:

#+begin_src til
func normalize_scope_bindings(mut scope: TypeScope)
#+end_src

* type_file
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_file
:group: Compiler frontend
:END:

#+begin_src til
proc type_file(path: Str, mut ctx: Context) returns shallow I32
#+end_src

* type_repl_delta
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_repl_delta
:group: Compiler frontend
:END:

#+begin_src til
proc type_repl_delta(path: Str, mut program: Expr, mut ctx: Context) returns shallow I32
#+end_src

* rhs_is_clone_fcall
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.rhs_is_clone_fcall
:group: Compiler frontend
:END:

#+begin_src til
func rhs_is_clone_fcall(rhs: Expr) returns shallow Bool
#+end_src

* assign_target_is_func_local
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.assign_target_is_func_local
:group: Compiler frontend
:END:

#+begin_src til
func assign_target_is_func_local(mut scope: TypeScope, name: Str) returns shallow Bool
#+end_src

* is_numeric_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.is_numeric_type
:group: Compiler frontend
:END:

#+begin_src til
func is_numeric_type(t: Type) returns shallow Bool
#+end_src

* is_integral_numeric_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.is_integral_numeric_type
:group: Compiler frontend
:END:

#+begin_src til
func is_integral_numeric_type(t: Type) returns shallow Bool
#+end_src

* literal_in_range
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.literal_in_range
:group: Compiler frontend
:END:

#+begin_src til
func literal_in_range(val_str: Str, target: Type) returns shallow Bool
#+end_src

* type_from_name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_from_name
:group: Compiler frontend
:END:

#+begin_src til
func type_from_name(name: Str, mut scope: TypeScope, mut ctx: Context) returns Type
#+end_src

* resolve_type_alias
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.resolve_type_alias
:group: Compiler frontend
:END:

#+begin_src til
func resolve_type_alias(scope: TypeScope, name: Str) returns ref Str
#+end_src

* resolve_type_alias_for_name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.resolve_type_alias_for_name
:group: Compiler frontend
:END:

#+begin_src til
func resolve_type_alias_for_name(scope: TypeScope, name: Str) returns ref Str
#+end_src

* usize_type
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.usize_type
:group: Compiler frontend
:END:

#+begin_src til
func usize_type(mut scope: TypeScope, mut ctx: Context) returns Type
#+end_src

* type_has_cmp
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_has_cmp
:group: Compiler frontend
:END:

#+begin_src til
func type_has_cmp(scope: TypeScope, type_name: Str) returns shallow Bool
#+end_src

* expr_uses_var
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.expr_uses_var
:group: Compiler frontend
:END:

#+begin_src til
func expr_uses_var(e: Expr, name: Str) returns shallow Bool
#+end_src

* expr_contains_decl
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.expr_contains_decl
:group: Compiler frontend
:END:

#+begin_src til
func expr_contains_decl(e: Expr, name: Str) returns shallow Bool
#+end_src

* expr_used_in_nested_func
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.expr_used_in_nested_func
:group: Compiler frontend
:END:

#+begin_src til
func expr_used_in_nested_func(e: Expr, name: Str) returns shallow Bool
#+end_src

* type_prefix
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_prefix
:group: Compiler frontend
:END:

#+begin_src til
func type_prefix(t: Type) returns Str
#+end_src

* type_to_name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.type_to_name
:group: Compiler frontend
:END:

#+begin_src til
func type_to_name(t: Type) returns Str
#+end_src

* make_closure_delete_call
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.make_closure_delete_call
:group: Compiler frontend
:END:

#+begin_src til
func make_closure_delete_call(var_name: Str, src: Expr) returns Expr
#+end_src

* make_delete_call
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.make_delete_call
:group: Compiler frontend
:END:

#+begin_src til
func make_delete_call(var_name: Str, shallow type: Type, shallow arg_is_own: Bool, shallow call_free: Bool, src: Expr) returns shallow Option__Expr
#+end_src

* transfer_is_shallow_field_value_copy
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.transfer_is_shallow_field_value_copy
:group: Compiler frontend
:END:

#+begin_src til
func transfer_is_shallow_field_value_copy(e: Expr, var_name: Str, scope: TypeScope) returns shallow Bool
#+end_src

* make_free_call
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.make_free_call
:group: Compiler frontend
:END:

#+begin_src til
func make_free_call(var_name: Str, shallow type: Type, src: Expr) returns Expr
#+end_src

* make_clone_call
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.make_clone_call
:group: Compiler frontend
:END:

#+begin_src til
func make_clone_call(type_name: Str, shallow type: Type, arg: Expr, src: Expr) returns Expr
#+end_src

* make_ns_call
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.make_ns_call
:group: Compiler frontend
:END:

#+begin_src til
func make_ns_call(sname: Str, method: Str, shallow ret_type: Type, src: Expr) returns Expr
#+end_src

* variadic_array_type_name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.variadic_array_type_name
:group: Compiler frontend
:END:

#+begin_src til
func variadic_array_type_name(scope: TypeScope, elem_type: Str) returns Str
#+end_src

* arg_addressed_ident
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.arg_addressed_ident
:group: Compiler frontend
:END:

#+begin_src til
func arg_addressed_ident(arg: Expr) returns shallow Option__ref_Str
#+end_src

* expr_transfers_own
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.expr_transfers_own
:group: Compiler frontend
:END:

#+begin_src til
func expr_transfers_own(e: Expr, var_name: Str, scope: TypeScope, ctx: Context) returns shallow Bool
#+end_src

* FactIndex
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.FactIndex
:group: Compiler frontend
:END:

#+begin_src til
struct FactIndex {
    mut filt : U64
    mut idx : Map__Str_USize
namespace:
    func clone(self: FactIndex) returns FactIndex
    func delete(own self: FactIndex, shallow call_free: Bool)
    func hash(self: FactIndex, hasher: HashFn) returns shallow U64
    func size() returns shallow USize
}
#+end_src

* fact_bit_search
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fact_bit_search
:group: Compiler frontend
:END:

#+begin_src til
func fact_bit_search(idx: Map__Str_USize, name: Str) returns shallow I64
#+end_src

* fact_bit_of
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fact_bit_of
:group: Compiler frontend
:END:

#+begin_src til
func fact_bit_of(fi: FactIndex, name: Str) returns shallow I64
#+end_src

* fact_bit_record
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fact_bit_record
:group: Compiler frontend
:END:

#+begin_src til
func fact_bit_record(mut mask: Vec__U64, shallow base: USize, shallow bit: USize)
#+end_src

* fact_record_name
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fact_record_name
:group: Compiler frontend
:END:

#+begin_src til
func fact_record_name(fi: FactIndex, name: Str, shallow base: USize, mut mask: Vec__U64)
#+end_src

* expr_collect_ptr_escapes
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.expr_collect_ptr_escapes
:group: Compiler frontend
:END:

#+begin_src til
func expr_collect_ptr_escapes(e: Expr, fi: FactIndex, shallow base: USize, mut out: Vec__U64)
#+end_src

* expr_collect_stmt_facts
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.expr_collect_stmt_facts
:group: Compiler frontend
:END:

#+begin_src til
func expr_collect_stmt_facts(e: Expr, scope: TypeScope, shallow want_transfers: Bool, shallow transfers_on: Bool, fi: FactIndex, shallow base: USize, mut uses: Vec__U64, mut decls: Vec__U64, mut nested: Vec__U64, mut escapes: Vec__U64, mut transfers: Vec__U64)
#+end_src

* RootBits
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.RootBits
:group: Compiler frontend
:END:

#+begin_src til
struct RootBits {
    mut alias : U64
    mut into : U64
    mut carried : U64
    mut provisional : U64
namespace:
    func eq(a: RootBits, b: RootBits) returns shallow Bool
    func to_str(_self: RootBits) returns Str
    func bor(self: RootBits, other: RootBits) returns RootBits
    func all(self: RootBits) returns shallow U64
    func is_zero(self: RootBits) returns shallow Bool
    func clone(self: RootBits) returns RootBits
    func delete(own self: RootBits, shallow call_free: Bool)
    func hash(self: RootBits, hasher: HashFn) returns shallow U64
    func cmp(a: RootBits, b: RootBits) returns shallow I64
    func size() returns shallow USize
    func lt(a: RootBits, b: RootBits) returns shallow Bool
    func gt(a: RootBits, b: RootBits) returns shallow Bool
    func neq(a: RootBits, b: RootBits) returns shallow Bool
    func lte(a: RootBits, b: RootBits) returns shallow Bool
    func gte(a: RootBits, b: RootBits) returns shallow Bool
}
#+end_src

* fcall_is_get_method
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fcall_is_get_method
:group: Compiler frontend
:END:

#+begin_src til
func fcall_is_get_method(fcall: Expr) returns shallow Bool
#+end_src

* fcall_returns_ref
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fcall_returns_ref
:group: Compiler frontend
:END:

#+begin_src til
func fcall_returns_ref(fcall: Expr, scope: TypeScope) returns shallow I32
#+end_src

* fcall_returns_shallow
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.fcall_returns_shallow
:group: Compiler frontend
:END:

#+begin_src til
func fcall_returns_shallow(fcall: Expr, scope: TypeScope, ctx: Context) returns shallow I32
#+end_src

* Vec__CtorArg
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg
:group: Compiler frontend
:END:

#+begin_src til
struct Vec__CtorArg {
    own mut data : U8
    mut count : USize
    mut cap : USize
namespace:
    func new() returns Vec__CtorArg
    func with_capacity(shallow n: USize) returns Vec__CtorArg
    func len(self: Vec__CtorArg) returns shallow USize
    func clear(mut self: Vec__CtorArg)
    func delete_marked(mut self: Vec__CtorArg, marks: Dynamic)
    func push(mut self: Vec__CtorArg, own val: priv___src_self_typer_til__CtorArg)
    func append(mut self: Vec__CtorArg, own other: Vec__CtorArg)
    func take(mut self: Vec__CtorArg) returns Vec__CtorArg
    func move_to(own self: Vec__CtorArg, mut dest: Vec__CtorArg)
    func move_from(mut self: Vec__CtorArg, own other: Vec__CtorArg)
    func unsafe_get(self: Vec__CtorArg, i: USize) returns ref priv___src_self_typer_til__CtorArg
    func get(self: Vec__CtorArg, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_typer_til__CtorArg
    func pop(mut self: Vec__CtorArg) returns shallow priv___src_self_typer_til__CtorArg
    func remove_at(mut self: Vec__CtorArg, shallow i: USize, mut _err_kind: I64)
    func take_prefix(mut self: Vec__CtorArg, shallow n: USize) returns Vec__CtorArg
    func truncate(mut self: Vec__CtorArg, shallow n: USize)
    func unsafe_set(mut self: Vec__CtorArg, shallow i: USize, own val: priv___src_self_typer_til__CtorArg)
    func set(mut self: Vec__CtorArg, shallow i: USize, own val: priv___src_self_typer_til__CtorArg, mut _err_kind: I64)
    func push_take(mut self: Vec__CtorArg, mut src: Vec__CtorArg, shallow i: USize)
    func delete(own self: Vec__CtorArg, shallow call_free: Bool)
    func clone(self: Vec__CtorArg) returns Vec__CtorArg
    func size() returns shallow USize
}
#+end_src

* Vec__CtorArg.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.new
:group: Compiler frontend
:END:

Create a new empty Vec for elements of type T. Lazy: no allocation
until the first push -- an empty Vec is (data=NULL, count=0, cap=0),
and the grow sites below seed cap 0->1 on the first insert. This keeps
the many containers that stay empty (e.g. the unused maps in a fresh
Scope) allocation-free, which is the dominant per-call interpreter cost.

#+begin_src til
func Vec__CtorArg.new() returns Vec__CtorArg
#+end_src

* Vec__CtorArg.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.with_capacity
:group: Compiler frontend
:END:

Create an empty Vec pre-sized for ~n~ elements, so pushing up to ~n~
items reallocs zero times. Use at call sites where the final length is
known up front (cloning a Vec of known length, building a fixed arg
list, ...) to avoid the 1->2->4->...->n grow-and-realloc churn that
~new()~ + repeated ~push~ pays. n=0 behaves like new(): lazy-empty,
no allocation (the grow sites seed cap 0->1 on the first insert).

#+begin_src til
func Vec__CtorArg.with_capacity(shallow n: USize) returns Vec__CtorArg
#+end_src

* Vec__CtorArg.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.clear
:group: Compiler frontend
:END:

Drop all live elements via elem_delete but keep the allocated
storage and element-type metadata so the Vec can be reused.

#+begin_src til
func Vec__CtorArg.clear(mut self: Vec__CtorArg)
#+end_src

* Vec__CtorArg.delete_marked
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.delete_marked
:group: Compiler frontend
:END:

Drop the elements flagged in ~marks~ (a byte-per-element buffer,
nonzero = drop, at least self.count entries) via elem_delete, then
compact the survivors forward and update count. This is the
container home for the scavenger's mark/sweep/compact, which used
to reach into data/count directly.

#+begin_src til
func Vec__CtorArg.delete_marked(mut self: Vec__CtorArg, marks: Dynamic)
#+end_src

* Vec__CtorArg.push
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.push
:group: Compiler frontend
:END:

Append an element to the end. ~val~ is owned: after this call the
caller must not use the value passed -- clone it first if needed.

#+begin_src til
func Vec__CtorArg.push(mut self: Vec__CtorArg, own val: priv___src_self_typer_til__CtorArg)
#+end_src

* Vec__CtorArg.append
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.append
:group: Compiler frontend
:END:

Consume the contents of ~other~ by appending them to ~self~.
~other~ is taken by ownership and will be empty after the call.

#+begin_src til
func Vec__CtorArg.append(mut self: Vec__CtorArg, own other: Vec__CtorArg)
#+end_src

* Vec__CtorArg.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.take
:group: Compiler frontend
:END:

Take the contents out: the returned Vec owns self's buffer and
self is left lazy-empty. No element is copied or cloned.

This is how a struct FIELD hands its contents over
(~mut old := body.children.take()~): a field cannot be an ~own~
argument or receiver, because the callee would then free the
ADDRESS OF THE FIELD -- the compiler dies with "free(): invalid
pointer" compiling itself. Everything the caller can give away
uses the two move forms below instead.

#+begin_src til
func Vec__CtorArg.take(mut self: Vec__CtorArg) returns Vec__CtorArg
#+end_src

* Vec__CtorArg.move_to
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.move_to
:group: Compiler frontend
:END:

Give self's contents to ~dest~, which drops whatever it held.
SELF is consumed, so the receiver is the owned one and the call
spells the type out: ~Vec(T).move_to(own src, dest)~.

The three fields move as BYTES on purpose:
~dest.data = self.data~ drops dest's old pointer (right) and then
~self.data = 0~ drops the pointer dest just adopted -- a double
free, which is what the emitted C does with field assignment.
Blanking the source leaves a genuinely valid lazy-empty Vec, so
a later push on it allocates afresh instead of reallocating a
buffer that now belongs to someone else.

#+begin_src til
func Vec__CtorArg.move_to(own self: Vec__CtorArg, mut dest: Vec__CtorArg)
#+end_src

* Vec__CtorArg.move_from
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.move_from
:group: Compiler frontend
:END:

Take ~other~'s contents, dropping whatever self held. OTHER is
consumed -- it is the value being emptied, so it is the owned
argument: ~dest.move_from(own src)~.

#+begin_src til
func Vec__CtorArg.move_from(mut self: Vec__CtorArg, own other: Vec__CtorArg)
#+end_src

* Vec__CtorArg.unsafe_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.unsafe_get
:group: Compiler frontend
:END:

Unchecked element access: return a reference to the element at
index ~i~ with NO bounds check. The caller must prove ~i < len()~.
This is the unchecked core that ~get~ wraps; for-in uses it
directly because its ~_fi < len()~ termination test already
proves the index in bounds (issue #284).

#+begin_src til
func Vec__CtorArg.unsafe_get(self: Vec__CtorArg, i: USize) returns ref priv___src_self_typer_til__CtorArg
#+end_src

* Vec__CtorArg.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.get
:group: Compiler frontend
:END:

Return a reference to the element at index ~i~. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i]~
to panic on a bad index. The reference is valid until the
next mutation.

#+begin_src til
func Vec__CtorArg.get(self: Vec__CtorArg, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_typer_til__CtorArg
#+end_src

* Vec__CtorArg.pop
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.pop
:group: Compiler frontend
:END:

Remove and return the last element. Panics if empty. The caller
takes ownership of the returned value.

#+begin_src til
func Vec__CtorArg.pop(mut self: Vec__CtorArg) returns shallow priv___src_self_typer_til__CtorArg
#+end_src

* Vec__CtorArg.remove_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.remove_at
:group: Compiler frontend
:END:

Remove and drop the element at ~i~, shifting later elements left.

#+begin_src til
func Vec__CtorArg.remove_at(mut self: Vec__CtorArg, shallow i: USize, mut _err_kind: I64)
#+end_src

* Vec__CtorArg.take_prefix
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.take_prefix
:group: Compiler frontend
:END:

Split off the first ~n~ elements into a new Vec. Panics if ~n~
exceeds self.len(). The remaining elements shift to the front.

#+begin_src til
func Vec__CtorArg.take_prefix(mut self: Vec__CtorArg, shallow n: USize) returns Vec__CtorArg
#+end_src

* Vec__CtorArg.truncate
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.truncate
:group: Compiler frontend
:END:

Drop the elements from index ~n~ to the end, freeing each via
elem_delete, and set count to ~n~ (the survivors [0, n) are left
untouched). Panics if ~n~ exceeds len. This is the container home
for a pop-and-free-the-tail loop shrinking a Vec back to a mark.

#+begin_src til
func Vec__CtorArg.truncate(mut self: Vec__CtorArg, shallow n: USize)
#+end_src

* Vec__CtorArg.unsafe_set
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.unsafe_set
:group: Compiler frontend
:END:

Overwrite the element at index ~i~ without a bounds check, dropping
the old value. Caller guarantees ~i < self.count~; the write-side
mirror of unsafe_get (issue #284).

#+begin_src til
func Vec__CtorArg.unsafe_set(mut self: Vec__CtorArg, shallow i: USize, own val: priv___src_self_typer_til__CtorArg)
#+end_src

* Vec__CtorArg.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.set
:group: Compiler frontend
:END:

Overwrite the element at index ~i~. ~val~ is owned. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i] = val~
(or ~vec.set(i, own val)!~) to panic on a bad index.

#+begin_src til
func Vec__CtorArg.set(mut self: Vec__CtorArg, shallow i: USize, own val: priv___src_self_typer_til__CtorArg, mut _err_kind: I64)
#+end_src

* Vec__CtorArg.push_take
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.push_take
:group: Compiler frontend
:END:

Move bytes of src[i] into self (push). Source slot is zeroed so that
src's eventual elem_delete on it is a no-op (relies on the same
count==0/data==NULL convention used by take_children and Vec.delete).

#+begin_src til
func Vec__CtorArg.push_take(mut self: Vec__CtorArg, mut src: Vec__CtorArg, shallow i: USize)
#+end_src

* Vec__CtorArg.delete
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.delete
:group: Compiler frontend
:END:

Drop each element via elem_delete, free storage, then free self
unless ~call_free~ is false.

#+begin_src til
func Vec__CtorArg.delete(own self: Vec__CtorArg, shallow call_free: Bool)
#+end_src

* Vec__CtorArg.clone
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CtorArg.clone
:group: Compiler frontend
:END:

Deep-copy the Vec and all its elements via elem_clone.

#+begin_src til
func Vec__CtorArg.clone(self: Vec__CtorArg) returns Vec__CtorArg
#+end_src

* Map__Str_RootBits
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits
:group: Compiler frontend
:END:

#+begin_src til
struct Map__Str_RootBits {
    mut keys : Vec__Str
    mut values : Vec__RootBits
namespace:
    func new() returns Map__Str_RootBits
    func with_capacity(shallow n: USize) returns Map__Str_RootBits
    func len(self: Map__Str_RootBits) returns shallow USize
    func clear(mut self: Map__Str_RootBits)
    func has(self: Map__Str_RootBits, key: Str) returns shallow Bool
    func get(self: Map__Str_RootBits, key: Str, mut _err_kind: I64) returns ref RootBits
    func set(mut self: Map__Str_RootBits, key: Str, own val: RootBits)
    func remove(mut self: Map__Str_RootBits, key: Str) returns shallow Bool
    func delete(own self: Map__Str_RootBits, shallow call_free: Bool)
    func clone(self: Map__Str_RootBits) returns Map__Str_RootBits
    func hash(self: Map__Str_RootBits, hasher: HashFn) returns shallow U64
    func size() returns shallow USize
}
#+end_src

* Map__Str_RootBits.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits.new
:group: Compiler frontend
:END:

Create an empty Map of the types provided for the key and values respectively.
The key type must implement ~cmp~.

#+begin_src til
func Map__Str_RootBits.new() returns Map__Str_RootBits
#+end_src

* Map__Str_RootBits.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits.with_capacity
:group: Compiler frontend
:END:

Create an empty Map pre-sized for ~n~ entries, so inserting up to
~n~ reallocs neither backing Vec (Vec.with_capacity's
counterpart). n=0 behaves like new(): lazy-empty, no allocation.

#+begin_src til
func Map__Str_RootBits.with_capacity(shallow n: USize) returns Map__Str_RootBits
#+end_src

* Map__Str_RootBits.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits.clear
:group: Compiler frontend
:END:

Drop all live keys and values but keep the allocated storage so the Map can be reused.

#+begin_src til
func Map__Str_RootBits.clear(mut self: Map__Str_RootBits)
#+end_src

* Map__Str_RootBits.has
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits.has
:group: Compiler frontend
:END:

True if a value exists for the given key.

#+begin_src til
func Map__Str_RootBits.has(self: Map__Str_RootBits, key: Str) returns shallow Bool
#+end_src

* Map__Str_RootBits.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits.get
:group: Compiler frontend
:END:

Return a ref to the value for ~key~. Throws KeyNotFound if
~key~ is absent; call as ~map.get(k)!~ (or ~map[k]~) to panic
on a missing key.

#+begin_src til
func Map__Str_RootBits.get(self: Map__Str_RootBits, key: Str, mut _err_kind: I64) returns ref RootBits
#+end_src

* Map__Str_RootBits.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits.set
:group: Compiler frontend
:END:

Insert or overwrite the value for ~key~. The value is owned.

#+begin_src til
func Map__Str_RootBits.set(mut self: Map__Str_RootBits, key: Str, own val: RootBits)
#+end_src

* Map__Str_RootBits.remove
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Map__Str_RootBits.remove
:group: Compiler frontend
:END:

Remove ~key~, dropping its key and value. Returns false if absent.

#+begin_src til
func Map__Str_RootBits.remove(mut self: Map__Str_RootBits, key: Str) returns shallow Bool
#+end_src

* Vec__CoverageNode
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode
:group: Compiler frontend
:END:

#+begin_src til
struct Vec__CoverageNode {
    own mut data : U8
    mut count : USize
    mut cap : USize
namespace:
    func new() returns Vec__CoverageNode
    func with_capacity(shallow n: USize) returns Vec__CoverageNode
    func len(self: Vec__CoverageNode) returns shallow USize
    func clear(mut self: Vec__CoverageNode)
    func delete_marked(mut self: Vec__CoverageNode, marks: Dynamic)
    func push(mut self: Vec__CoverageNode, own val: priv___src_self_typer_til__CoverageNode)
    func append(mut self: Vec__CoverageNode, own other: Vec__CoverageNode)
    func take(mut self: Vec__CoverageNode) returns Vec__CoverageNode
    func move_to(own self: Vec__CoverageNode, mut dest: Vec__CoverageNode)
    func move_from(mut self: Vec__CoverageNode, own other: Vec__CoverageNode)
    func unsafe_get(self: Vec__CoverageNode, i: USize) returns ref priv___src_self_typer_til__CoverageNode
    func get(self: Vec__CoverageNode, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_typer_til__CoverageNode
    func pop(mut self: Vec__CoverageNode) returns priv___src_self_typer_til__CoverageNode
    func remove_at(mut self: Vec__CoverageNode, shallow i: USize, mut _err_kind: I64)
    func take_prefix(mut self: Vec__CoverageNode, shallow n: USize) returns Vec__CoverageNode
    func truncate(mut self: Vec__CoverageNode, shallow n: USize)
    func unsafe_set(mut self: Vec__CoverageNode, shallow i: USize, own val: priv___src_self_typer_til__CoverageNode)
    func set(mut self: Vec__CoverageNode, shallow i: USize, own val: priv___src_self_typer_til__CoverageNode, mut _err_kind: I64)
    func push_take(mut self: Vec__CoverageNode, mut src: Vec__CoverageNode, shallow i: USize)
    func delete(own self: Vec__CoverageNode, shallow call_free: Bool)
    func clone(self: Vec__CoverageNode) returns Vec__CoverageNode
    func size() returns shallow USize
}
#+end_src

* Vec__CoverageNode.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.new
:group: Compiler frontend
:END:

Create a new empty Vec for elements of type T. Lazy: no allocation
until the first push -- an empty Vec is (data=NULL, count=0, cap=0),
and the grow sites below seed cap 0->1 on the first insert. This keeps
the many containers that stay empty (e.g. the unused maps in a fresh
Scope) allocation-free, which is the dominant per-call interpreter cost.

#+begin_src til
func Vec__CoverageNode.new() returns Vec__CoverageNode
#+end_src

* Vec__CoverageNode.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.with_capacity
:group: Compiler frontend
:END:

Create an empty Vec pre-sized for ~n~ elements, so pushing up to ~n~
items reallocs zero times. Use at call sites where the final length is
known up front (cloning a Vec of known length, building a fixed arg
list, ...) to avoid the 1->2->4->...->n grow-and-realloc churn that
~new()~ + repeated ~push~ pays. n=0 behaves like new(): lazy-empty,
no allocation (the grow sites seed cap 0->1 on the first insert).

#+begin_src til
func Vec__CoverageNode.with_capacity(shallow n: USize) returns Vec__CoverageNode
#+end_src

* Vec__CoverageNode.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.clear
:group: Compiler frontend
:END:

Drop all live elements via elem_delete but keep the allocated
storage and element-type metadata so the Vec can be reused.

#+begin_src til
func Vec__CoverageNode.clear(mut self: Vec__CoverageNode)
#+end_src

* Vec__CoverageNode.delete_marked
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.delete_marked
:group: Compiler frontend
:END:

Drop the elements flagged in ~marks~ (a byte-per-element buffer,
nonzero = drop, at least self.count entries) via elem_delete, then
compact the survivors forward and update count. This is the
container home for the scavenger's mark/sweep/compact, which used
to reach into data/count directly.

#+begin_src til
func Vec__CoverageNode.delete_marked(mut self: Vec__CoverageNode, marks: Dynamic)
#+end_src

* Vec__CoverageNode.push
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.push
:group: Compiler frontend
:END:

Append an element to the end. ~val~ is owned: after this call the
caller must not use the value passed -- clone it first if needed.

#+begin_src til
func Vec__CoverageNode.push(mut self: Vec__CoverageNode, own val: priv___src_self_typer_til__CoverageNode)
#+end_src

* Vec__CoverageNode.append
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.append
:group: Compiler frontend
:END:

Consume the contents of ~other~ by appending them to ~self~.
~other~ is taken by ownership and will be empty after the call.

#+begin_src til
func Vec__CoverageNode.append(mut self: Vec__CoverageNode, own other: Vec__CoverageNode)
#+end_src

* Vec__CoverageNode.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.take
:group: Compiler frontend
:END:

Take the contents out: the returned Vec owns self's buffer and
self is left lazy-empty. No element is copied or cloned.

This is how a struct FIELD hands its contents over
(~mut old := body.children.take()~): a field cannot be an ~own~
argument or receiver, because the callee would then free the
ADDRESS OF THE FIELD -- the compiler dies with "free(): invalid
pointer" compiling itself. Everything the caller can give away
uses the two move forms below instead.

#+begin_src til
func Vec__CoverageNode.take(mut self: Vec__CoverageNode) returns Vec__CoverageNode
#+end_src

* Vec__CoverageNode.move_to
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.move_to
:group: Compiler frontend
:END:

Give self's contents to ~dest~, which drops whatever it held.
SELF is consumed, so the receiver is the owned one and the call
spells the type out: ~Vec(T).move_to(own src, dest)~.

The three fields move as BYTES on purpose:
~dest.data = self.data~ drops dest's old pointer (right) and then
~self.data = 0~ drops the pointer dest just adopted -- a double
free, which is what the emitted C does with field assignment.
Blanking the source leaves a genuinely valid lazy-empty Vec, so
a later push on it allocates afresh instead of reallocating a
buffer that now belongs to someone else.

#+begin_src til
func Vec__CoverageNode.move_to(own self: Vec__CoverageNode, mut dest: Vec__CoverageNode)
#+end_src

* Vec__CoverageNode.move_from
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.move_from
:group: Compiler frontend
:END:

Take ~other~'s contents, dropping whatever self held. OTHER is
consumed -- it is the value being emptied, so it is the owned
argument: ~dest.move_from(own src)~.

#+begin_src til
func Vec__CoverageNode.move_from(mut self: Vec__CoverageNode, own other: Vec__CoverageNode)
#+end_src

* Vec__CoverageNode.unsafe_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.unsafe_get
:group: Compiler frontend
:END:

Unchecked element access: return a reference to the element at
index ~i~ with NO bounds check. The caller must prove ~i < len()~.
This is the unchecked core that ~get~ wraps; for-in uses it
directly because its ~_fi < len()~ termination test already
proves the index in bounds (issue #284).

#+begin_src til
func Vec__CoverageNode.unsafe_get(self: Vec__CoverageNode, i: USize) returns ref priv___src_self_typer_til__CoverageNode
#+end_src

* Vec__CoverageNode.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.get
:group: Compiler frontend
:END:

Return a reference to the element at index ~i~. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i]~
to panic on a bad index. The reference is valid until the
next mutation.

#+begin_src til
func Vec__CoverageNode.get(self: Vec__CoverageNode, shallow i: USize, mut _err_kind: I64) returns ref priv___src_self_typer_til__CoverageNode
#+end_src

* Vec__CoverageNode.pop
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.pop
:group: Compiler frontend
:END:

Remove and return the last element. Panics if empty. The caller
takes ownership of the returned value.

#+begin_src til
func Vec__CoverageNode.pop(mut self: Vec__CoverageNode) returns priv___src_self_typer_til__CoverageNode
#+end_src

* Vec__CoverageNode.remove_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.remove_at
:group: Compiler frontend
:END:

Remove and drop the element at ~i~, shifting later elements left.

#+begin_src til
func Vec__CoverageNode.remove_at(mut self: Vec__CoverageNode, shallow i: USize, mut _err_kind: I64)
#+end_src

* Vec__CoverageNode.take_prefix
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.take_prefix
:group: Compiler frontend
:END:

Split off the first ~n~ elements into a new Vec. Panics if ~n~
exceeds self.len(). The remaining elements shift to the front.

#+begin_src til
func Vec__CoverageNode.take_prefix(mut self: Vec__CoverageNode, shallow n: USize) returns Vec__CoverageNode
#+end_src

* Vec__CoverageNode.truncate
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.truncate
:group: Compiler frontend
:END:

Drop the elements from index ~n~ to the end, freeing each via
elem_delete, and set count to ~n~ (the survivors [0, n) are left
untouched). Panics if ~n~ exceeds len. This is the container home
for a pop-and-free-the-tail loop shrinking a Vec back to a mark.

#+begin_src til
func Vec__CoverageNode.truncate(mut self: Vec__CoverageNode, shallow n: USize)
#+end_src

* Vec__CoverageNode.unsafe_set
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.unsafe_set
:group: Compiler frontend
:END:

Overwrite the element at index ~i~ without a bounds check, dropping
the old value. Caller guarantees ~i < self.count~; the write-side
mirror of unsafe_get (issue #284).

#+begin_src til
func Vec__CoverageNode.unsafe_set(mut self: Vec__CoverageNode, shallow i: USize, own val: priv___src_self_typer_til__CoverageNode)
#+end_src

* Vec__CoverageNode.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.set
:group: Compiler frontend
:END:

Overwrite the element at index ~i~. ~val~ is owned. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i] = val~
(or ~vec.set(i, own val)!~) to panic on a bad index.

#+begin_src til
func Vec__CoverageNode.set(mut self: Vec__CoverageNode, shallow i: USize, own val: priv___src_self_typer_til__CoverageNode, mut _err_kind: I64)
#+end_src

* Vec__CoverageNode.push_take
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.push_take
:group: Compiler frontend
:END:

Move bytes of src[i] into self (push). Source slot is zeroed so that
src's eventual elem_delete on it is a no-op (relies on the same
count==0/data==NULL convention used by take_children and Vec.delete).

#+begin_src til
func Vec__CoverageNode.push_take(mut self: Vec__CoverageNode, mut src: Vec__CoverageNode, shallow i: USize)
#+end_src

* Vec__CoverageNode.delete
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.delete
:group: Compiler frontend
:END:

Drop each element via elem_delete, free storage, then free self
unless ~call_free~ is false.

#+begin_src til
func Vec__CoverageNode.delete(own self: Vec__CoverageNode, shallow call_free: Bool)
#+end_src

* Vec__CoverageNode.clone
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__CoverageNode.clone
:group: Compiler frontend
:END:

Deep-copy the Vec and all its elements via elem_clone.

#+begin_src til
func Vec__CoverageNode.clone(self: Vec__CoverageNode) returns Vec__CoverageNode
#+end_src

* Vec__RootBits
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits
:group: Compiler frontend
:END:

#+begin_src til
struct Vec__RootBits {
    own mut data : U8
    mut count : USize
    mut cap : USize
namespace:
    func new() returns Vec__RootBits
    func with_capacity(shallow n: USize) returns Vec__RootBits
    func len(self: Vec__RootBits) returns shallow USize
    func clear(mut self: Vec__RootBits)
    func delete_marked(mut self: Vec__RootBits, marks: Dynamic)
    func push(mut self: Vec__RootBits, own val: RootBits)
    func append(mut self: Vec__RootBits, own other: Vec__RootBits)
    func take(mut self: Vec__RootBits) returns Vec__RootBits
    func move_to(own self: Vec__RootBits, mut dest: Vec__RootBits)
    func move_from(mut self: Vec__RootBits, own other: Vec__RootBits)
    func unsafe_get(self: Vec__RootBits, i: USize) returns ref RootBits
    func get(self: Vec__RootBits, shallow i: USize, mut _err_kind: I64) returns ref RootBits
    func pop(mut self: Vec__RootBits) returns RootBits
    func remove_at(mut self: Vec__RootBits, shallow i: USize, mut _err_kind: I64)
    func take_prefix(mut self: Vec__RootBits, shallow n: USize) returns Vec__RootBits
    func truncate(mut self: Vec__RootBits, shallow n: USize)
    func unsafe_set(mut self: Vec__RootBits, shallow i: USize, own val: RootBits)
    func set(mut self: Vec__RootBits, shallow i: USize, own val: RootBits, mut _err_kind: I64)
    func push_take(mut self: Vec__RootBits, mut src: Vec__RootBits, shallow i: USize)
    func delete(own self: Vec__RootBits, shallow call_free: Bool)
    func clone(self: Vec__RootBits) returns Vec__RootBits
    func size() returns shallow USize
}
#+end_src

* Vec__RootBits.new
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.new
:group: Compiler frontend
:END:

Create a new empty Vec for elements of type T. Lazy: no allocation
until the first push -- an empty Vec is (data=NULL, count=0, cap=0),
and the grow sites below seed cap 0->1 on the first insert. This keeps
the many containers that stay empty (e.g. the unused maps in a fresh
Scope) allocation-free, which is the dominant per-call interpreter cost.

#+begin_src til
func Vec__RootBits.new() returns Vec__RootBits
#+end_src

* Vec__RootBits.with_capacity
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.with_capacity
:group: Compiler frontend
:END:

Create an empty Vec pre-sized for ~n~ elements, so pushing up to ~n~
items reallocs zero times. Use at call sites where the final length is
known up front (cloning a Vec of known length, building a fixed arg
list, ...) to avoid the 1->2->4->...->n grow-and-realloc churn that
~new()~ + repeated ~push~ pays. n=0 behaves like new(): lazy-empty,
no allocation (the grow sites seed cap 0->1 on the first insert).

#+begin_src til
func Vec__RootBits.with_capacity(shallow n: USize) returns Vec__RootBits
#+end_src

* Vec__RootBits.clear
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.clear
:group: Compiler frontend
:END:

Drop all live elements via elem_delete but keep the allocated
storage and element-type metadata so the Vec can be reused.

#+begin_src til
func Vec__RootBits.clear(mut self: Vec__RootBits)
#+end_src

* Vec__RootBits.delete_marked
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.delete_marked
:group: Compiler frontend
:END:

Drop the elements flagged in ~marks~ (a byte-per-element buffer,
nonzero = drop, at least self.count entries) via elem_delete, then
compact the survivors forward and update count. This is the
container home for the scavenger's mark/sweep/compact, which used
to reach into data/count directly.

#+begin_src til
func Vec__RootBits.delete_marked(mut self: Vec__RootBits, marks: Dynamic)
#+end_src

* Vec__RootBits.push
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.push
:group: Compiler frontend
:END:

Append an element to the end. ~val~ is owned: after this call the
caller must not use the value passed -- clone it first if needed.

#+begin_src til
func Vec__RootBits.push(mut self: Vec__RootBits, own val: RootBits)
#+end_src

* Vec__RootBits.append
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.append
:group: Compiler frontend
:END:

Consume the contents of ~other~ by appending them to ~self~.
~other~ is taken by ownership and will be empty after the call.

#+begin_src til
func Vec__RootBits.append(mut self: Vec__RootBits, own other: Vec__RootBits)
#+end_src

* Vec__RootBits.take
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.take
:group: Compiler frontend
:END:

Take the contents out: the returned Vec owns self's buffer and
self is left lazy-empty. No element is copied or cloned.

This is how a struct FIELD hands its contents over
(~mut old := body.children.take()~): a field cannot be an ~own~
argument or receiver, because the callee would then free the
ADDRESS OF THE FIELD -- the compiler dies with "free(): invalid
pointer" compiling itself. Everything the caller can give away
uses the two move forms below instead.

#+begin_src til
func Vec__RootBits.take(mut self: Vec__RootBits) returns Vec__RootBits
#+end_src

* Vec__RootBits.move_to
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.move_to
:group: Compiler frontend
:END:

Give self's contents to ~dest~, which drops whatever it held.
SELF is consumed, so the receiver is the owned one and the call
spells the type out: ~Vec(T).move_to(own src, dest)~.

The three fields move as BYTES on purpose:
~dest.data = self.data~ drops dest's old pointer (right) and then
~self.data = 0~ drops the pointer dest just adopted -- a double
free, which is what the emitted C does with field assignment.
Blanking the source leaves a genuinely valid lazy-empty Vec, so
a later push on it allocates afresh instead of reallocating a
buffer that now belongs to someone else.

#+begin_src til
func Vec__RootBits.move_to(own self: Vec__RootBits, mut dest: Vec__RootBits)
#+end_src

* Vec__RootBits.move_from
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.move_from
:group: Compiler frontend
:END:

Take ~other~'s contents, dropping whatever self held. OTHER is
consumed -- it is the value being emptied, so it is the owned
argument: ~dest.move_from(own src)~.

#+begin_src til
func Vec__RootBits.move_from(mut self: Vec__RootBits, own other: Vec__RootBits)
#+end_src

* Vec__RootBits.unsafe_get
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.unsafe_get
:group: Compiler frontend
:END:

Unchecked element access: return a reference to the element at
index ~i~ with NO bounds check. The caller must prove ~i < len()~.
This is the unchecked core that ~get~ wraps; for-in uses it
directly because its ~_fi < len()~ termination test already
proves the index in bounds (issue #284).

#+begin_src til
func Vec__RootBits.unsafe_get(self: Vec__RootBits, i: USize) returns ref RootBits
#+end_src

* Vec__RootBits.get
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.get
:group: Compiler frontend
:END:

Return a reference to the element at index ~i~. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i]~
to panic on a bad index. The reference is valid until the
next mutation.

#+begin_src til
func Vec__RootBits.get(self: Vec__RootBits, shallow i: USize, mut _err_kind: I64) returns ref RootBits
#+end_src

* Vec__RootBits.pop
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.pop
:group: Compiler frontend
:END:

Remove and return the last element. Panics if empty. The caller
takes ownership of the returned value.

#+begin_src til
func Vec__RootBits.pop(mut self: Vec__RootBits) returns RootBits
#+end_src

* Vec__RootBits.remove_at
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.remove_at
:group: Compiler frontend
:END:

Remove and drop the element at ~i~, shifting later elements left.

#+begin_src til
func Vec__RootBits.remove_at(mut self: Vec__RootBits, shallow i: USize, mut _err_kind: I64)
#+end_src

* Vec__RootBits.take_prefix
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.take_prefix
:group: Compiler frontend
:END:

Split off the first ~n~ elements into a new Vec. Panics if ~n~
exceeds self.len(). The remaining elements shift to the front.

#+begin_src til
func Vec__RootBits.take_prefix(mut self: Vec__RootBits, shallow n: USize) returns Vec__RootBits
#+end_src

* Vec__RootBits.truncate
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.truncate
:group: Compiler frontend
:END:

Drop the elements from index ~n~ to the end, freeing each via
elem_delete, and set count to ~n~ (the survivors [0, n) are left
untouched). Panics if ~n~ exceeds len. This is the container home
for a pop-and-free-the-tail loop shrinking a Vec back to a mark.

#+begin_src til
func Vec__RootBits.truncate(mut self: Vec__RootBits, shallow n: USize)
#+end_src

* Vec__RootBits.unsafe_set
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.unsafe_set
:group: Compiler frontend
:END:

Overwrite the element at index ~i~ without a bounds check, dropping
the old value. Caller guarantees ~i < self.count~; the write-side
mirror of unsafe_get (issue #284).

#+begin_src til
func Vec__RootBits.unsafe_set(mut self: Vec__RootBits, shallow i: USize, own val: RootBits)
#+end_src

* Vec__RootBits.set
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.set
:group: Compiler frontend
:END:

Overwrite the element at index ~i~. ~val~ is owned. Throws
OutOfBounds if ~i~ is past the end; call as ~vec[i] = val~
(or ~vec.set(i, own val)!~) to panic on a bad index.

#+begin_src til
func Vec__RootBits.set(mut self: Vec__RootBits, shallow i: USize, own val: RootBits, mut _err_kind: I64)
#+end_src

* Vec__RootBits.push_take
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.push_take
:group: Compiler frontend
:END:

Move bytes of src[i] into self (push). Source slot is zeroed so that
src's eventual elem_delete on it is a no-op (relies on the same
count==0/data==NULL convention used by take_children and Vec.delete).

#+begin_src til
func Vec__RootBits.push_take(mut self: Vec__RootBits, mut src: Vec__RootBits, shallow i: USize)
#+end_src

* Vec__RootBits.delete
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.delete
:group: Compiler frontend
:END:

Drop each element via elem_delete, free storage, then free self
unless ~call_free~ is false.

#+begin_src til
func Vec__RootBits.delete(own self: Vec__RootBits, shallow call_free: Bool)
#+end_src

* Vec__RootBits.clone
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.Vec__RootBits.clone
:group: Compiler frontend
:END:

Deep-copy the Vec and all its elements via elem_clone.

#+begin_src til
func Vec__RootBits.clone(self: Vec__RootBits) returns Vec__RootBits
#+end_src

* adopt__priv___src_self_typer_til__CtorArg
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.adopt__priv___src_self_typer_til__CtorArg
:group: Compiler frontend
:END:

#+begin_src til
func adopt__priv___src_self_typer_til__CtorArg(dest: Dynamic, own src: priv___src_self_typer_til__CtorArg)
#+end_src

* adopt__RootBits
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.adopt__RootBits
:group: Compiler frontend
:END:

#+begin_src til
func adopt__RootBits(dest: Dynamic, own src: RootBits)
#+end_src

* adopt__priv___src_self_typer_til__CoverageNode
:PROPERTIES:
:CUSTOM_ID: til.src.self.typer.adopt__priv___src_self_typer_til__CoverageNode
:group: Compiler frontend
:END:

#+begin_src til
func adopt__priv___src_self_typer_til__CoverageNode(dest: Dynamic, own src: priv___src_self_typer_til__CoverageNode)
#+end_src
